"""
NiCo business logic library.

Contains all non-HTTP helpers previously scattered in server.py.
Both the Flask web frontend (server.py) and the TUI can import from here
without any Flask dependency.
"""
from __future__ import annotations

import hashlib
import re
from pathlib import Path

from . import config_manager, generator, git_manager, hm_generator, importer
from .brix import (
    brix_content_to_bricks,
    extract_brick_blocks,
    inject_brick_blocks,
    strip_brick_blocks,
)

# ── File type classification ───────────────────────────────────────────────────

_FILENAME_TYPE_HINTS: dict[str, str] = {
    "hardware-configuration.nix": "hw",
    "flake.nix":                  "fl",
}

_VALID_FILE_TYPES = frozenset({"co", "nd", "fl", "mo", "hm", "hw"})
_READABLE_SUFFIXES = {".nix", ".lock", ".json", ".md"}
_WRITABLE_SUFFIXES = {".nix"}


def classify_filename(name: str) -> str | None:
    """Map a .nix filename to its NiCo type code. Returns None for non-.nix files."""
    if name in ('configuration.nix', 'default.nix'):
        return 'co'
    if name == 'flake.nix':
        return 'fl'
    if name == 'hardware-configuration.nix':
        return 'hw'
    if name == 'home.nix':
        return 'hm'
    if name.endswith('.nix'):
        return 'nd'
    return None


# ── nico-version header management ────────────────────────────────────────────

_VERSION_NOTYPE_RE = re.compile(
    r'^(# nico-version: )([0-9a-f]{8})', re.MULTILINE
)
_VERSION_WITHTYPE_RE = re.compile(
    r'^(# nico-version: )[a-z]+#([0-9a-f]{8})', re.MULTILINE
)
_VERSION_ANY_RE = re.compile(
    r'^# nico-version: (?:[a-z]+#)?[0-9a-f]{8}\n?', re.MULTILINE
)

NICO_HEADER = (
    "# Generated by NiCo – NixOS Configurator\n"
    "# Do not edit manually. Use NiCo or add custom Nix via Nix-Brix.\n"
)


def get_nico_type(content: str) -> str | None:
    """Return the file-type code from the nico-version line, or None if absent.

    Returns:
      'co', 'nd', 'fl', etc.  – explicit type present
      ''                       – nico-version line exists but has no type
      None                     – no nico-version line at all (external file)
    """
    m = re.search(
        r'^# nico-version: (?:([a-z]+)#)?[0-9a-f]{8}', content, re.MULTILINE
    )
    if not m:
        return None
    return m.group(1) or ""


def insert_type(content: str, ftype: str) -> str:
    """Rewrite the nico-version line to prepend <ftype># before the hash."""
    return _VERSION_NOTYPE_RE.sub(rf'\g<1>{ftype}#\g<2>', content, count=1)


def set_type_in_content(content: str, ftype: str) -> str:
    """Replace or insert the type code in the nico-version line, recomputing the hash.

    Handles all three cases:
      - type already present  → remove old line, recompute hash, write new line
      - no type, has hash     → remove old line, recompute hash, write new line
      - no nico-version line  → prepend nico-version line (+ NiCo header for CO only)
    """
    if _VERSION_ANY_RE.search(content):
        canonical = _VERSION_ANY_RE.sub('', content, count=1)
        h = hashlib.sha256(canonical.encode()).hexdigest()[:8]
        new_line = f"# nico-version: {ftype}#{h}\n"
        return _VERSION_ANY_RE.sub(new_line, content, count=1)
    if ftype == 'co':
        canonical = NICO_HEADER + content
        h = hashlib.sha256(canonical.encode()).hexdigest()[:8]
        nico_line = f"# nico-version: {ftype}#{h}\n"
        return f"{NICO_HEADER}{nico_line}{content}"
    h = hashlib.sha256(content.encode()).hexdigest()[:8]
    nico_line = f"# nico-version: {ftype}#{h}\n"
    return f"{nico_line}{content}"


# ── Brick helpers ──────────────────────────────────────────────────────────────

def brick_body(text: str) -> str:
    """Extract body lines from a formatted brick text (strips start/end marker lines)."""
    lines = text.splitlines(keepends=True)
    if len(lines) >= 2:
        return "".join(lines[1:-1])
    return ""


def modify_brick_in_file(
    nixos_dir: str,
    fname: str,
    modifier,  # callable: dict[str, dict] -> dict[str, dict]
) -> tuple[bool, str]:
    """Read fname, apply modifier(blocks) → new_blocks, rewrite with updated hash.

    Returns (success, error_key_or_empty).
    """
    root  = Path(nixos_dir).resolve()
    fpath = (root / fname).resolve()
    try:
        fpath.relative_to(root)
    except ValueError:
        return False, "ERR_SYSTEM_PATH"
    if not fpath.exists():
        return False, "ERR_FILE_NOT_FOUND"
    try:
        content = fpath.read_text(encoding="utf-8")
    except OSError:
        return False, "ERR_READ"

    ftype = get_nico_type(content)
    if ftype is None or ftype == "":
        ftype = "nd"

    if ftype == "hm":
        try:
            content, blocks = normalize_hm_content(content)
        except Exception:
            blocks = extract_brick_blocks(content)
    else:
        blocks = extract_brick_blocks(content)
    new_blocks = modifier(blocks)
    clean      = strip_brick_blocks(content)
    with_brick = inject_brick_blocks(clean, new_blocks)
    final      = set_type_in_content(with_brick, ftype)

    try:
        fpath.write_text(final, encoding="utf-8")
    except OSError:
        return False, "ERR_WRITE"

    return True, ""


# ── Home Manager patching ──────────────────────────────────────────────────────

def hm_patch_str(content: str, key: str, value: str) -> str:
    ek = re.escape(key)
    return re.sub(rf'({ek}\s*=\s*)"[^"]*"', rf'\1"{value}"', content)


def hm_patch_bool(content: str, key: str, value: bool) -> str:
    ek = re.escape(key)
    nv = "true" if value else "false"
    return re.sub(rf'({ek}\s*=\s*)(true|false)', rf'\g<1>{nv}', content)


def hm_patch_args(content: str, args: list) -> str:
    all_args = [a for a in args if a] + ["..."]
    new_header = "{ " + ", ".join(all_args) + " }:"
    return re.sub(r'^\s*\{[^}]*\}\s*:', new_header, content, count=1,
                  flags=re.MULTILINE | re.DOTALL)


def hm_patch_init_extra(content: str, new_extra: str) -> str:
    for shell, key in [("bash", "initExtra"), ("zsh", "initExtra"), ("fish", "shellInit")]:
        if not re.search(rf'programs\.{shell}\s*=\s*\{{', content):
            continue
        ek = re.escape(key)
        if new_extra:
            indented = "\n".join(f"      {ln}" for ln in new_extra.splitlines())
            def _repl(_m, _k=key, _ind=indented):
                return f"\n    {_k} = ''\n{_ind}\n    '';"
            patched = re.sub(
                rf'\s*{ek}\s*=\s*\'\'[\s\S]*?\'\'[ \t]*;',
                _repl, content, count=1
            )
            if patched != content:
                return patched
            def _ins(_m, _k=key, _ind=indented):
                body = _m.group(0)
                close = body.rfind("};")
                return body[:close] + f"    {_k} = ''\n{_ind}\n    '';\n  }};"
            return re.sub(
                rf'programs\.{shell}\s*=\s*\{{[\s\S]*?\n  \}};',
                _ins, content, count=1
            )
        else:
            return re.sub(
                rf'\s*{ek}\s*=\s*\'\'[\s\S]*?\'\'[ \t]*;',
                '', content, count=1
            )
    return content


def hm_patch_packages(content: str, packages: list) -> str:
    pkg_re = re.compile(
        r'(\s*)home\.packages\s*=(?:\s*with\s+pkgs\s*;)?\s*\[[\s\S]*?\]\s*;'
    )
    m = pkg_re.search(content)
    if m:
        indent = m.group(1).replace('\n', '')
        if packages:
            pkg_lines = "\n".join(f"{indent}  pkgs.{p}" for p in packages)
            new_block = f"{indent}home.packages = [\n{pkg_lines}\n{indent}];"
            return content[:m.start()] + "\n" + new_block + content[m.end():]
        return content[:m.start()] + content[m.end():]
    if packages:
        indent = "  "
        pkg_lines = "\n".join(f"{indent}  pkgs.{p}" for p in packages)
        new_block = f"\n{indent}home.packages = [\n{pkg_lines}\n{indent}];"
        return re.sub(r'(\n\}\n)', rf'{new_block}\1', content, count=1)
    return content


def hm_update_hash(content: str) -> str:
    canonical = re.sub(
        r'^# nico-version: (?:[a-z]+#)?[0-9a-f]{8}\n', '',
        content, count=1, flags=re.MULTILINE
    )
    new_hash = hashlib.sha256(canonical.encode()).hexdigest()[:8]
    return re.sub(
        r'^(# nico-version: (?:[a-z]+#)?)[0-9a-f]{8}',
        rf'\g<1>{new_hash}',
        content, count=1, flags=re.MULTILINE
    )


def normalize_hm_content(content: str) -> tuple[str, dict]:
    """Return normalized HM content plus extracted/derived brick blocks."""
    existing_bricks = extract_brick_blocks(content)
    clean_content   = strip_brick_blocks(content)
    hm              = importer.parse_home_config(clean_content)
    blocks          = dict(existing_bricks)
    rest            = importer.build_home_rest_brix(clean_content, hm)
    if rest.strip():
        rest_blocks = brix_content_to_bricks(rest, section="End", existing_blocks=blocks)
        blocks.update(rest_blocks)
    hm_data                  = dict(hm)
    hm_data["hm_brick_blocks"] = blocks
    return hm_generator.generate_home_nix(hm_data), blocks


# ── Flake host management ──────────────────────────────────────────────────────

def scan_flake_hosts(flake_path: Path) -> list[str]:
    """Scan an external flake.nix for nixosConfigurations host names."""
    try:
        content = flake_path.read_text(encoding="utf-8")
    except OSError:
        return []
    found: list[str] = []
    for m in re.finditer(r'nixosConfigurations\s*\.\s*"?([\w-]+)"?', content):
        h = m.group(1)
        if h not in found:
            found.append(h)
    return found


def get_flake_hosts(nixos_dir: str, data: dict) -> list[str]:
    """Return all flake host names for rebuild/dry-run, sourced from flake.nix on disk."""
    hosts: list[str] = []
    flake_path = Path(nixos_dir) / "flake.nix"

    if flake_path.exists():
        try:
            flake_data = dict(data)
            flake_data.update(importer.parse_flake_nix(flake_path.read_text(encoding="utf-8")))
            for h in flake_data.get("flake_hosts") or []:
                name = h.get("name", "")
                if name and name not in hosts:
                    hosts.append(name)
        except OSError:
            pass

    for h in data.get("flake_hosts") or []:
        name = h.get("name", "")
        if name and name not in hosts:
            hosts.append(name)

    if flake_path.exists():
        try:
            brix = extract_brick_blocks(flake_path.read_text(encoding="utf-8"))
            for bname, block in brix.items():
                if block.get("section") == "Outputs-Hosts" and bname not in hosts:
                    hosts.append(bname)
                elif bname == "outputs-declaration" and block.get("section") == "Outputs":
                    body = brick_body(block["text"])
                    for m in re.finditer(r'\b([\w-]+)\s*=\s*nixpkgs\.lib\.nixosSystem', body):
                        h = m.group(1)
                        if h not in hosts:
                            hosts.append(h)
        except OSError:
            pass

    if not hosts:
        single = (data.get("hostname") or "nixos").strip()
        if single:
            hosts.append(single)

    return hosts or ["nixos"]


def flake_outputs_modify_host(brix_text: str, action: str, host_name: str) -> str | None:
    """Add or remove a nixosSystem host entry inside the nixosConfigurations block
    of an outputs-declaration Brix body. Returns the modified body or None."""
    body = brick_body(brix_text)

    m = re.search(r'\bnixosConfigurations\s*=\s*\{', body)
    if not m:
        return None
    brace_start = body.index('{', m.start())
    depth, i, cfg_end = 0, brace_start, len(body)
    while i < len(body):
        if body[i] == '{':
            depth += 1
        elif body[i] == '}':
            depth -= 1
            if depth == 0:
                cfg_end = i
                break
        i += 1

    cfg_body = body[brace_start + 1:cfg_end]

    def _extract_system_block(text: str, sys_match) -> tuple[int, int]:
        bp = text.index('{', sys_match.end() - 1)
        d, j, end = 0, bp, len(text)
        while j < len(text):
            if text[j] == '{':
                d += 1
            elif text[j] == '}':
                d -= 1
                if d == 0:
                    end = j + 1
                    while end < len(text) and text[end] in ' \t':
                        end += 1
                    if end < len(text) and text[end] == ';':
                        end += 1
                    break
            j += 1
        return sys_match.start(), end

    if action == 'add':
        sys_m = re.search(
            r'\s+[\w-]+\s*=\s*nixpkgs\.lib\.nixosSystem\s*\{', cfg_body
        )
        if not sys_m:
            return None
        src_name = re.search(r'([\w-]+)\s*=\s*nixpkgs', sys_m.group()).group(1)
        start_pos, end_pos = _extract_system_block(cfg_body, sys_m)
        template_block = cfg_body[start_pos:end_pos]
        new_block = (
            template_block
            .replace(f'{src_name} =', f'{host_name} =', 1)
            .replace(f'./hosts/{src_name}/', f'./hosts/{host_name}/')
            .replace(f'./hosts/{src_name}', f'./hosts/{host_name}')
        )
        new_cfg_body = cfg_body.rstrip('\n') + '\n' + new_block + '\n'

    elif action == 'remove':
        sys_m = re.search(
            r'\s+' + re.escape(host_name) + r'\s*=\s*nixpkgs\.lib\.nixosSystem\s*\{',
            cfg_body,
        )
        if not sys_m:
            return None
        start_pos, end_pos = _extract_system_block(cfg_body, sys_m)
        new_cfg_body = cfg_body[:start_pos] + cfg_body[end_pos:]
    else:
        return None

    return body[:brace_start + 1] + new_cfg_body + body[cfg_end:]


# ── Path & security ────────────────────────────────────────────────────────────

_SAFE_NAME_RE = re.compile(r"^[^/\\]+$")

_FORBIDDEN_PATH_PREFIXES = [
    Path('/etc'), Path('/usr'), Path('/bin'), Path('/sbin'),
    Path('/lib'), Path('/lib64'), Path('/proc'), Path('/sys'),
    Path('/dev'), Path('/run'), Path('/boot'), Path('/nix/store'),
    Path('/root'), Path('/var'),
]


def validate_user_path(raw: str):
    """Validate a user-provided filesystem path.

    Returns (resolved_path, None) on success or (None, error_key) on failure.
    Blocks path traversal and known system directories.
    """
    if not raw or not raw.strip():
        return None, "ERR_NO_DIR"
    try:
        p = Path(raw).expanduser().resolve()
    except Exception:
        return None, "ERR_INVALID_PATH"
    for prefix in _FORBIDDEN_PATH_PREFIXES:
        try:
            p.relative_to(prefix)
            return None, "ERR_SYSTEM_PATH"
        except ValueError:
            pass
    return p, None


# ── Nix error output ───────────────────────────────────────────────────────────

def clean_nix_error(raw: str, tmpfile: str) -> str:
    """Sanitize nix error output: replace temp path, strip boilerplate."""
    cleaned = raw.replace(tmpfile, "<config>")
    lines   = cleaned.splitlines()
    while lines and not lines[0].strip():
        lines.pop(0)
    return "\n".join(lines)


# ── Shared filesystem helpers ────────────────────────────────────────────────

def _resolve_config_rel(root: Path, rel_path: str) -> Path:
    target = (root / rel_path).resolve()
    target.relative_to(root)
    return target


def list_config_tree(nixos_dir: str) -> dict:
    """Return the visible config tree, matching the web UI rules."""
    root = Path(nixos_dir).resolve()
    cfg_settings = config_manager.load_config_settings(nixos_dir)
    hm_dir = cfg_settings.get("hm_dir", "home").strip() or "home"
    app_settings = config_manager.get_app_settings()
    show_flake_lock = bool(app_settings.get("show_flake_lock", False))

    def _classify_by_path(item: Path) -> str | None:
        rel = item.relative_to(root)
        parts = rel.parts
        if len(parts) >= 2 and parts[0] == hm_dir:
            return "hm"
        return classify_filename(item.name)

    def _build_tree(directory: Path) -> list[dict]:
        entries: list[dict] = []
        try:
            items = sorted(directory.iterdir(), key=lambda p: (p.is_file(), p.name.lower()))
        except PermissionError:
            return entries
        for item in items:
            if item.name.startswith(".") or (item.name == "nico" and item.is_dir()):
                continue
            rel_path = str(item.relative_to(root))
            if item.is_dir():
                entries.append({
                    "name": item.name,
                    "type": "dir",
                    "path": rel_path,
                    "children": _build_tree(item),
                })
            elif item.suffix == ".nix":
                entries.append({
                    "name": item.name,
                    "type": "file",
                    "path": rel_path,
                    "file_type": _FILENAME_TYPE_HINTS.get(item.name) or _classify_by_path(item),
                })
            elif item.name == "flake.lock" and show_flake_lock:
                entries.append({
                    "name": item.name,
                    "type": "file",
                    "path": rel_path,
                    "file_type": "flk",
                })
        return entries

    return {"tree": _build_tree(root), "root": str(root)}


def read_config_file(nixos_dir: str, rel_path: str) -> dict:
    """Read a config-relative file with the same normalization rules as the web UI."""
    rel = (rel_path or "").strip()
    if not rel:
        raise ValueError("ERR_NO_PATH")

    root = Path(nixos_dir).resolve()
    target = _resolve_config_rel(root, rel)

    if target.suffix not in _READABLE_SUFFIXES:
        raise ValueError("ERR_FILE_TYPE")
    if not target.exists():
        raise FileNotFoundError("ERR_FILE_NOT_FOUND")

    content = target.read_text(encoding="utf-8")

    if target.name == "flake.lock":
        return {"content": content, "path": rel, "file_type": "flk", "writable": False}

    hint_type = _FILENAME_TYPE_HINTS.get(target.name)
    cfg_settings = config_manager.load_config_settings(nixos_dir)
    hm_dir = cfg_settings.get("hm_dir", "home").strip() or "home"
    rel_parts = Path(rel).parts
    path_type = "hm" if len(rel_parts) >= 2 and rel_parts[0] == hm_dir else None

    ftype = get_nico_type(content)
    if ftype == "":
        stamp = hint_type or path_type or classify_filename(target.name) or "nd"
        content = insert_type(content, stamp)
        try:
            target.write_text(content, encoding="utf-8")
        except OSError:
            pass
        ftype = stamp
    elif ftype is not None:
        override = hint_type or path_type
        if override and override != ftype:
            content = insert_type(content, override)
            try:
                target.write_text(content, encoding="utf-8")
            except OSError:
                pass
            ftype = override

    if ftype == "hm":
        try:
            content, _ = normalize_hm_content(content)
        except Exception:
            pass

    return {
        "content": content,
        "path": rel,
        "file_type": ftype,
        "writable": target.suffix in _WRITABLE_SUFFIXES,
    }


def write_raw_config_file(
    nixos_dir: str,
    rel_path: str,
    content: str,
    *,
    label: str = "",
    commit: bool = True,
) -> dict:
    """Write a raw .nix file inside the config directory."""
    rel = (rel_path or "").strip()
    if not rel:
        raise ValueError("ERR_NO_PATH")

    root = Path(nixos_dir).resolve()
    target = _resolve_config_rel(root, rel)

    if target.suffix not in _WRITABLE_SUFFIXES:
        raise ValueError("ERR_FILE_TYPE")

    cfg_settings = config_manager.load_config_settings(nixos_dir)
    hm_dir = cfg_settings.get("hm_dir", "home").strip() or "home"
    rel_parts = Path(rel).parts
    is_hm_path = len(rel_parts) >= 2 and rel_parts[0] == hm_dir
    if is_hm_path or classify_filename(target.name) == "hm":
        content, _ = normalize_hm_content(content)

    target.write_text(content, encoding="utf-8")

    if commit:
        try:
            git_manager.auto_commit(nixos_dir, label=label)
        except Exception:
            pass

    result = {"success": True, "written": [rel]}
    try:
        cfg = config_manager.load_config_settings(nixos_dir)
        if cfg.get("push_after_save"):
            ok, msg, code = git_manager.git_push(nixos_dir)
            result["pushed"] = ok
            result["push_error"] = "" if ok else msg
            result["push_error_code"] = "" if ok else code
    except Exception:
        pass
    return result


# ── Config load / write orchestration ─────────────────────────────────────────

def load_and_normalize_config(nixos_dir: str) -> dict:
    """
    Load config state from disk, normalize any externally-modified .nix files,
    and return the complete data dict (same shape as /api/config GET response).
    """
    data = config_manager.load_config(nixos_dir)

    cfg_nix = Path(nixos_dir) / "configuration.nix"
    if cfg_nix.exists():
        try:
            nix_content = cfg_nix.read_text(encoding="utf-8")
            hash_status = generator.check_version_hash(nix_content)
            if data is None:
                data = config_manager.get_defaults()
            if hash_status in ("modified", "no_hash"):
                existing_bricks = extract_brick_blocks(nix_content)
                nix_without_bricks = strip_brick_blocks(nix_content)
                recognized = importer.parse_config(nix_without_bricks)
                data.update(recognized)
                config_manager.save_config(nixos_dir, data)
                rest = importer.build_rest_brix(nix_without_bricks, recognized)
                blocks = dict(existing_bricks)
                if rest.strip():
                    rest_blocks = brix_content_to_bricks(rest, section="Start", existing_blocks=blocks)
                    blocks.update(rest_blocks)
                data["brick_blocks"] = blocks
                cfg_nix.write_text(
                    generator.generate_configuration_nix(data), encoding="utf-8"
                )
            else:
                data["brick_blocks"] = extract_brick_blocks(nix_content)
        except OSError:
            pass

    if data is None:
        config_manager.init_nico_dir(nixos_dir)
        data = config_manager.load_config(nixos_dir)

    config_manager.migrate_nico_json(nixos_dir)

    flake_nix_path = Path(nixos_dir) / "flake.nix"
    if flake_nix_path.exists():
        try:
            flake_content = flake_nix_path.read_text(encoding="utf-8")
            parsed = importer.parse_flake_nix(flake_content)
            data.update(parsed)
            config_manager.save_config(nixos_dir, data)
            if get_nico_type(flake_content) is not None and \
                    "# Generated by NiCo" not in flake_content:
                flake_brix = importer.build_flake_brix(flake_content)
                flake_brix = importer.ensure_flake_host_bricks(flake_content, flake_brix)
                data["flake_brick_blocks"] = flake_brix
                flake_nix_path.write_text(
                    generator.generate_flake_nix(data, nixos_dir=nixos_dir),
                    encoding="utf-8",
                )
                flake_content = flake_nix_path.read_text(encoding="utf-8")
            flake_brix = extract_brick_blocks(flake_content)
            data["flake_brick_blocks"] = importer.ensure_flake_host_bricks(flake_content, flake_brix)
        except OSError:
            pass

    home_nix_path = Path(nixos_dir) / "home.nix"
    if home_nix_path.exists():
        try:
            home_content = home_nix_path.read_text(encoding="utf-8")
            hash_status = generator.check_version_hash(home_content)
            if get_nico_type(home_content) is not None and hash_status in ("modified", "no_hash"):
                existing_bricks = extract_brick_blocks(home_content)
                home_without_bricks = strip_brick_blocks(home_content)
                hm = importer.parse_home_config(home_without_bricks)
                rest = importer.build_home_rest_brix(home_without_bricks, hm)
                blocks = dict(existing_bricks)
                if rest.strip():
                    rest_blocks = brix_content_to_bricks(rest, section="End", existing_blocks=blocks)
                    blocks.update(rest_blocks)
                data["hm_brick_blocks"] = blocks
                home_data = dict(hm)
                home_data["hm_brick_blocks"] = blocks
                home_nix_path.write_text(
                    hm_generator.generate_home_nix(home_data), encoding="utf-8"
                )
            else:
                data["hm_brick_blocks"] = extract_brick_blocks(home_content)
        except OSError:
            pass

    modified = []
    for fname in ("configuration.nix", "flake.nix", "home.nix"):
        p = Path(nixos_dir) / fname
        if p.exists():
            if generator.check_version_hash(p.read_text()) == "modified":
                modified.append(fname)
    data["_modified_files"] = modified
    return data


def write_config_files(
    nixos_dir: str,
    data: dict,
    *,
    commit: bool = True,
    label: str = "",
) -> dict:
    """
    Write generated .nix files to nixos_dir.
    Returns {"success": True, "written": [...]} plus optional push fields.
    """
    nixos_path = Path(nixos_dir)
    conf_file = nixos_path / "configuration.nix"

    if conf_file.exists():
        data["brick_blocks"] = extract_brick_blocks(conf_file.read_text())

    conf_file.write_text(generator.generate_configuration_nix(data))
    written = ["configuration.nix"]

    if data.get("flakes"):
        flake_file = nixos_path / "flake.nix"
        _flake_content = flake_file.read_text(encoding="utf-8") if flake_file.exists() else None
        _flake_nico = _flake_content is None or get_nico_type(_flake_content) is not None
        if _flake_nico:
            if _flake_content:
                data.update(importer.parse_flake_nix(_flake_content))
                flake_brix = extract_brick_blocks(_flake_content)
                flake_brix = importer.ensure_flake_host_bricks(_flake_content, flake_brix)
                if flake_brix:
                    data["flake_brick_blocks"] = flake_brix
            flake_file.write_text(generator.generate_flake_nix(data, nixos_dir=str(nixos_path)))
            written.append("flake.nix")

    hm = dict(data.get("home_manager") or {})
    if hm.get("enabled"):
        home_file = nixos_path / "home.nix"
        _home_nico = (
            not home_file.exists()
            or get_nico_type(home_file.read_text(encoding="utf-8")) is not None
        )
        if _home_nico:
            if home_file.exists():
                try:
                    home_content = home_file.read_text(encoding="utf-8")
                    hm_brix = extract_brick_blocks(home_content)
                    if hm_brix:
                        data["hm_brick_blocks"] = hm_brix
                    elif not data.get("hm_brick_blocks"):
                        clean_home = strip_brick_blocks(home_content)
                        recognized_home = importer.parse_home_config(clean_home)
                        rest = importer.build_home_rest_brix(clean_home, recognized_home)
                        if rest.strip():
                            data["hm_brick_blocks"] = brix_content_to_bricks(rest, section="End")
                except OSError:
                    pass
            hm["hm_brick_blocks"] = data.get("hm_brick_blocks", {})
            home_file.write_text(hm_generator.generate_home_nix(hm))
            written.append("home.nix")

    if commit:
        try:
            git_manager.auto_commit(nixos_dir, label=label)
        except Exception:
            pass

    result: dict = {"success": True, "written": written}
    try:
        cfg = config_manager.load_config_settings(nixos_dir)
        if cfg.get("push_after_save"):
            ok, msg, code = git_manager.git_push(nixos_dir)
            result["pushed"] = ok
            result["push_error"] = "" if ok else msg
            result["push_error_code"] = "" if ok else code
    except Exception:
        pass
    return result


# ── Validation ─────────────────────────────────────────────────────────────────

def run_enabled_validation(
    nixos_dir: str,
    config: dict | None,
    host: str | None = None,
) -> list[dict]:
    """Run all enabled validation rules and return a list of finding dicts."""
    from . import validator as _val
    cfg_settings  = config_manager.load_config_settings(nixos_dir)
    enabled_rules = cfg_settings.get("validation_rules") or _val.default_validation_rules()
    return _val.run_validation(nixos_dir, enabled_rules, config or {}, host=host)
