"""
Nix file generator.
Produces configuration.nix (and optionally flake.nix) from NiCo's config data.
Section markers use the format  `  # ── SectionName ──…`  so the frontend
can split the preview into collapsible sections that sync with the form.
"""

import hashlib
import re
import shlex

from .brix import format_brick, inject_brick_blocks
from .importer import flake_host_brick_name, flake_host_section

_NIX_ATTR_RE = re.compile(r"^[A-Za-z_][A-Za-z0-9_'-]*$")


def nix_esc(value) -> str:
    """Escape a value for use inside a double-quoted Nix string ("...")."""
    return (str(value)
            .replace("\\", "\\\\")
            .replace('"', '\\"')
            .replace("${", "\\${")
            .replace("\r", "")
            .replace("\n", "\\n")
            .replace("\t", "\\t"))


def nix_ind_esc(value) -> str:
    """Escape a value for use inside an indented Nix string (''...'')."""
    return str(value).replace("''", "'''").replace("${", "''${")


def nix_attr(name) -> str:
    """Render a name as a Nix attrpath component; quote when not a plain identifier."""
    s = str(name)
    return s if _NIX_ATTR_RE.match(s) else f'"{nix_esc(s)}"'


def _int_or(value, default: int) -> int:
    """Parse value as int; fall back to default instead of raising."""
    try:
        return int(str(value).strip())
    except (TypeError, ValueError):
        return default

# Matches nico-version lines in both formats:
#   # nico-version: a3f8c2d1          (legacy / no type)
#   # nico-version: co#a3f8c2d1       (with type code)
_VERSION_RE = re.compile(
    r'^# nico-version: (?:[a-z]+#)?([0-9a-f]{8})(?:#[pr])?\n', re.MULTILINE
)
# Matches only the legacy format (no type prefix) – used to detect missing type
_VERSION_RE_NOTYPE = re.compile(
    r'^# nico-version: ([0-9a-f]{8})\n', re.MULTILINE
)


def content_hash(content: str) -> str:
    """8-hex sha256 digest used by all nico-version lines."""
    return hashlib.sha256(content.encode()).hexdigest()[:8]


def _add_version_hash(content: str, ftype: str = "") -> str:
    """Insert '# nico-version: [type#]<hash>' on line 2 of content.
    The hash covers the content *without* the nico-version line itself.
    ftype: optional type code (e.g. 'co', 'fl') prepended as '<ftype>#'.
    """
    h = content_hash(content)
    prefix = f"{ftype}#" if ftype else ""
    lines = content.split("\n")
    lines.insert(1, f"# nico-version: {prefix}{h}")
    return "\n".join(lines)


def check_version_hash(file_content: str) -> str:
    """Check whether a NiCo-generated file has been externally modified.

    Returns:
      'ok'       – hash present and matches
      'modified' – hash present but doesn't match (file was edited outside NiCo)
      'no_hash'  – no nico-version line (file predates this feature or wasn't generated by NiCo)
    """
    m = _VERSION_RE.search(file_content)
    if not m:
        return "no_hash"
    stored = m.group(1)
    # Remove the entire nico-version line (with or without type prefix) to get canonical content
    canonical = _VERSION_RE.sub("", file_content, count=1)
    computed = content_hash(canonical)
    return "ok" if computed == stored else "modified"

# Width of the section marker line (total chars)
_MARKER_WIDTH = 78


def _section(name: str) -> str:
    """Return a section marker line:  # ── Name ──────────────────"""
    dashes = "─" * max(1, _MARKER_WIDTH - len(name) - 6)
    return f"\n  # ── {name} {dashes}"


def _has_section_brix(brix: dict, section: str) -> bool:
    """Return True if any brick block belongs to *section*."""
    return any(b.get("section") == section for b in brix.values())


_DE_SNIPPETS: dict[str, str] = {
    "none": "",
    "gnome": """\
  services.xserver.enable = true;
  services.xserver.displayManager.gdm.enable = true;
  services.xserver.desktopManager.gnome.enable = true;""",
    "kde": """\
  services.xserver.enable = true;
  services.displayManager.sddm.enable = true;
  services.desktopManager.plasma6.enable = true;""",
    "xfce": """\
  services.xserver.enable = true;
  services.xserver.displayManager.lightdm.enable = true;
  services.xserver.desktopManager.xfce.enable = true;""",
    "i3": """\
  services.xserver.enable = true;
  services.xserver.windowManager.i3.enable = true;""",
    "sway":     "  programs.sway.enable = true;",
    "hyprland": "  programs.hyprland.enable = true;",
}


# ── shared section builders ───────────────────────────────────────────────────
# Used by generate_configuration_nix (host_mode=False) and generate_host_nix
# (host_mode=True). Host data is sparse; defaults that only the CO form
# pre-fills (networkmanager, stateVersion line, 32bit gating) differ per mode.

_SHELL_PKGS = {"zsh": "zsh", "fish": "fish", "nushell": "nushell"}


def _sec_boot(data: dict, brix: dict) -> "list[str]":
    boot_loader         = data.get("boot_loader", "none") or "none"
    boot_kernel_params  = (data.get("boot_kernel_params", "") or "").strip()
    boot_initrd_systemd = data.get("boot_initrd_systemd", False)
    plymouth_enabled    = data.get("plymouth_enabled", False)
    plymouth_theme      = (data.get("plymouth_theme", "") or "").strip()
    if not (boot_loader != "none" or boot_kernel_params or boot_initrd_systemd
            or plymouth_enabled or _has_section_brix(brix, "Boot")):
        return []
    boot_efi_can_touch = data.get("boot_efi_can_touch", False)
    boot_efi_mount     = (data.get("boot_efi_mount_point", "/boot") or "/boot").strip()
    boot_config_limit  = _int_or(data.get("boot_config_limit"), 5)
    lines = [_section("Boot")]
    if boot_loader != "none":
        if boot_loader == "systemd-boot":
            lines += [
                "  boot.loader.systemd-boot.enable = true;",
                f"  boot.loader.systemd-boot.configurationLimit = {boot_config_limit};",
            ]
        elif boot_loader == "grub":
            lines += ["  boot.loader.grub.enable = true;"]
        lines += [f'  boot.loader.efi.canTouchEfiVariables = {"true" if boot_efi_can_touch else "false"};']
        if boot_efi_mount != "/boot":
            lines += [f'  boot.loader.efi.efiSysMountPoint = "{nix_esc(boot_efi_mount)}";']
    if boot_kernel_params:
        params = " ".join(f'"{nix_esc(p)}"' for p in boot_kernel_params.split())
        lines += [f"  boot.kernelParams = [ {params} ];"]
    if boot_initrd_systemd:
        lines += ["  boot.initrd.systemd.enable = true;"]
    if plymouth_enabled:
        lines += ["  boot.plymouth.enable = true;"]
        if plymouth_theme:
            lines += [f'  boot.plymouth.theme = "{nix_esc(plymouth_theme)}";']
    return lines


def _sec_system(data: dict, *, host_mode: bool) -> "list[str]":
    hostname = (data.get("hostname") or "").strip()
    if host_mode:
        # Sparse host file: no stateVersion, section only when set
        if not hostname:
            return []
        return [_section("System"), f'  networking.hostName = "{nix_esc(hostname)}";']
    state_version = (data.get("state_version") or "").strip()
    lines = [_section("System")]
    if hostname:
        lines += [f'  networking.hostName = "{nix_esc(hostname)}";']
    lines += [
        f'  system.stateVersion = "{nix_esc(state_version)}";' if state_version
        else '  # system.stateVersion = "";  # TODO: set NixOS state version'
    ]
    return lines


def _sec_localization(data: dict, brix: dict) -> "list[str]":
    loc_lines = []
    timezone = (data.get("timezone") or "").strip()
    locale   = (data.get("locale") or "").strip()
    if timezone:
        loc_lines += [f'  time.timeZone = "{nix_esc(timezone)}";', ""]
    if locale:
        loc_lines += [f'  i18n.defaultLocale = "{nix_esc(locale)}";']
    extra_locale = data.get("extra_locale", "")
    if extra_locale:
        loc_lines += [
            "  i18n.extraLocaleSettings = {",
            f'    LC_ADDRESS        = "{nix_esc(extra_locale)}";',
            f'    LC_IDENTIFICATION = "{nix_esc(extra_locale)}";',
            f'    LC_MEASUREMENT    = "{nix_esc(extra_locale)}";',
            f'    LC_MONETARY       = "{nix_esc(extra_locale)}";',
            f'    LC_NAME           = "{nix_esc(extra_locale)}";',
            f'    LC_NUMERIC        = "{nix_esc(extra_locale)}";',
            f'    LC_PAPER          = "{nix_esc(extra_locale)}";',
            f'    LC_TELEPHONE      = "{nix_esc(extra_locale)}";',
            f'    LC_TIME           = "{nix_esc(extra_locale)}";',
            "  };",
        ]
    kb_layout = data.get("keyboard_layout", "")
    if kb_layout:
        loc_lines += [
            "",
            "  services.xserver.xkb = {",
            f'    layout = "{nix_esc(kb_layout)}";',
            f'    variant = "{nix_esc(data.get("keyboard_variant", ""))}";',
            "  };",
        ]
    if data.get("keyboard_console"):
        loc_lines += [f'  console.keyMap = "{nix_esc(data["keyboard_console"])}";']
    if loc_lines or _has_section_brix(brix, "Lokalisierung"):
        return [_section("Lokalisierung")] + loc_lines
    return []


def _sec_network(data: dict, brix: dict, *, nm_default: bool) -> "list[str]":
    net_lines = []
    if data.get("networkmanager", nm_default):
        net_lines += ["  networking.networkmanager.enable = true;"]
    if data.get("ssh"):
        net_lines += ["  services.openssh.enable = true;"]
    if data.get("firewall_disable"):
        net_lines += ["  networking.firewall.enable = false;"]
    if data.get("firewall_tcp_enable"):
        fw_tcp = [p for p in (data.get("firewall_tcp_ports") or "").split() if p.isdigit()]
        if fw_tcp:
            net_lines += [f"  networking.firewall.allowedTCPPorts = [ {' '.join(fw_tcp)} ];"]
    if data.get("firewall_udp_enable"):
        fw_udp = [p for p in (data.get("firewall_udp_ports") or "").split() if p.isdigit()]
        if fw_udp:
            net_lines += [f"  networking.firewall.allowedUDPPorts = [ {' '.join(fw_udp)} ];"]
    if net_lines or _has_section_brix(brix, "Netzwerk"):
        return [_section("Netzwerk")] + net_lines
    return []


def _sec_services(data: dict, brix: dict) -> "list[str]":
    svc_lines = []
    if data.get("printing"):
        svc_lines += ["  services.printing.enable = true;"]
    if data.get("avahi"):
        svc_lines += [
            "  services.avahi = {",
            "    enable = true;",
            "    nssmdns4 = true;",
            "    openFirewall = true;",
            "  };",
        ]
    if data.get("bluetooth"):
        svc_lines += ["  hardware.bluetooth.enable = true;"]
        if data.get("blueman"):
            svc_lines += ["  services.blueman.enable = true;"]
    if data.get("libinput"):
        svc_lines += ["  services.libinput.enable = true;"]
    if data.get("fprintd"):
        svc_lines += ["  services.fprintd.enable = true;"]
    if data.get("pcscd"):
        svc_lines += ["  services.pcscd.enable = true;"]
    if data.get("sunshine"):
        svc_lines += ["  services.sunshine.enable = true;"]
    if svc_lines or _has_section_brix(brix, "Services"):
        return [_section("Services")] + svc_lines
    return []


def _sec_desktop(data: dict, brix: dict) -> "list[str]":
    de = data.get("desktop_environment", "none") or "none"
    de_snippet = _DE_SNIPPETS.get(de, "")
    autologin_user = data.get("autologin_user", "")
    if not (de_snippet or autologin_user or _has_section_brix(brix, "Desktop")):
        return []
    lines = [_section("Desktop")]
    if de_snippet:
        lines += [de_snippet]
    if autologin_user:
        lines += [
            "  services.displayManager.autoLogin = {",
            "    enable = true;",
            f'    user = "{nix_esc(autologin_user)}";',
            "  };",
        ]
    return lines


def _sec_audio(data: dict, brix: dict, *, gate_32bit: bool) -> "list[str]":
    audio_lines = []
    if data.get("pipewire"):
        audio_lines += [
            "  services.pulseaudio.enable = false;",
            "  security.rtkit.enable = true;",
            "  services.pipewire = {",
            "    enable = true;",
            "    alsa.enable = true;",
            "    pulse.enable = true;",
            "  };",
        ]
    # gate_32bit (CO): 32bit only together with pipewire; host emits it alone
    if data.get("pipewire_32bit") and (data.get("pipewire") or not gate_32bit):
        audio_lines += ["  services.pipewire.alsa.support32Bit = true;"]
    if audio_lines or _has_section_brix(brix, "Audio"):
        return [_section("Audio")] + audio_lines
    return []


def _user_block_lines(name: str, description: str, uid: str, password: str,
                      groups: "list[str]", shell: str, extra_nix: str) -> "list[str]":
    groups_str = " ".join(f'"{nix_esc(g)}"' for g in groups)
    lines = [f"  users.users.{nix_attr(name)} = {{", "    isNormalUser = true;"]
    if description:
        lines += [f'    description = "{nix_esc(description)}";']
    if uid.isdigit():
        lines += [f"    uid = {uid};"]
    if password:
        lines += [f'    initialPassword = "{nix_esc(password)}";']
    lines += [f"    extraGroups = [ {groups_str} ];"]
    if shell != "bash":
        shell_pkg = _SHELL_PKGS.get(shell, shell)
        lines += [f"    shell = pkgs.{shell_pkg};"]
    for ln in extra_nix.splitlines():
        if ln.strip():
            lines += [f"    {ln.strip()}"]
    lines += ["  };"]
    return lines


def _sec_users(data: dict, brix: dict) -> "list[str]":
    username = data.get("username", "")
    if not username:
        return [_section("Benutzer")] if _has_section_brix(brix, "Benutzer") else []
    user_groups_list  = data.get("user_groups", ["wheel", "networkmanager"])
    user_groups_extra = [g for g in (data.get("user_groups_extra") or "").split() if g]
    user_all_groups   = sorted(set(user_groups_list + user_groups_extra)) or ["wheel"]
    lines = [_section("Benutzer")]
    lines += _user_block_lines(
        username,
        data.get("user_description", ""),
        str(data.get("user_uid") or "").strip(),
        data.get("user_initial_password", ""),
        user_all_groups,
        data.get("user_shell", "bash") or "bash",
        (data.get("user_extra_nix") or "").strip(),
    )
    if data.get("guest_user", False):
        # Guest user block (no password, no sudo)
        lines += [
            "  users.users.gast = {",
            "    isNormalUser = true;",
            '    initialPassword = "";',
            "  };",
        ]
    return lines


def _sec_extra_users(data: dict) -> "list[str]":
    lines = []
    for eu in data.get("extra_users", []):
        eu_name = (eu.get("username") or "").strip()
        if not eu_name:
            continue
        lines += _user_block_lines(
            eu_name,
            (eu.get("description") or "").strip(),
            str(eu.get("uid") or "").strip(),
            (eu.get("initial_password") or "").strip(),
            eu.get("groups") or ["wheel", "networkmanager"],
            (eu.get("shell") or "bash").strip(),
            (eu.get("extra_nix") or "").strip(),
        )
    return lines


def _sec_programs(data: dict, brix: dict) -> "list[str]":
    prog_lines = []
    if data.get("allowUnfree"):
        prog_lines += ["  nixpkgs.config.allowUnfree = true;"]
    if data.get("steam"):
        prog_lines += ["  programs.steam.enable = true;"]
    if data.get("appimage"):
        prog_lines += [
            "  programs.appimage = {",
            "    enable = true;",
            "    binfmt = true;",
            "  };",
        ]
    if data.get("firefox"):
        ff_lang  = data.get("firefox_lang_packs", "")
        ff_prefs = data.get("firefox_prefs", "")
        lang_list  = [p.strip() for p in ff_lang.split(",") if p.strip()] if ff_lang else []
        pref_lines = [l.strip() for l in ff_prefs.splitlines() if l.strip()] if ff_prefs else []
        if lang_list or pref_lines:
            prog_lines += ["  programs.firefox = {", "    enable = true;"]
            if lang_list:
                packs = " ".join(f'"{nix_esc(p)}"' for p in lang_list)
                prog_lines += [f"    languagePacks = [ {packs} ];"]
            if pref_lines:
                prog_lines += ["    preferences = {"]
                for pl in pref_lines:
                    prog_lines += [f"      {pl}"]
                prog_lines += ["    };"]
            prog_lines += ["  };"]
        else:
            prog_lines += ["  programs.firefox.enable = true;"]
    if data.get("flatpak_enable"):
        prog_lines += ["  services.flatpak.enable = true;"]
    flatpak_remotes = [r for r in (data.get("flatpak_remotes") or []) if r.get("name") and r.get("url")]
    if flatpak_remotes:
        script_body = "\n".join(
            f"      flatpak remote-add --if-not-exists {nix_ind_esc(shlex.quote(r['name']))} {nix_ind_esc(shlex.quote(r['url']))}"
            for r in flatpak_remotes
        )
        prog_lines += [
            "  systemd.services.flatpak-repo = {",
            "    wantedBy = [ \"multi-user.target\" ];",
            "    path = [ pkgs.flatpak ];",
            "    script = ''",
            script_body,
            "    '';",
            "  };",
        ]
    packages = sorted(p["attr"] for p in data.get("packages", []) if p.get("enabled", True))
    if packages:
        pkg_lines = "\n".join(f"    {attr}" for attr in packages)
        prog_lines += [
            "  environment.systemPackages = with pkgs; [",
            pkg_lines,
            "  ];",
        ]
    if prog_lines or _has_section_brix(brix, "Programme"):
        return [_section("Programme")] + prog_lines
    return []


def _sec_fonts(data: dict, brix: dict) -> "list[str]":
    fonts_checked = data.get("fonts", [])
    fonts_extra   = [l.strip() for l in (data.get("fonts_extra") or "").strip().splitlines() if l.strip()]
    fonts_all     = sorted(set(fonts_checked + fonts_extra))
    if fonts_all:
        font_lines = "\n".join(f"    {f}" for f in fonts_all)
        return [
            _section("Schriftarten"),
            "  fonts.packages = with pkgs; [",
            font_lines,
            "  ];",
        ]
    if _has_section_brix(brix, "Schriftarten"):
        return [_section("Schriftarten")]
    return []


def _sec_nix_system(data: dict, brix: dict) -> "list[str]":
    nix_lines = []
    user_shell = data.get("user_shell", "bash") or "bash"
    if user_shell in ("zsh", "fish"):
        nix_lines += [f"  programs.{user_shell}.enable = true;"]
    if data.get("flakes"):
        nix_lines += ['  nix.settings.experimental-features = [ "nix-command" "flakes" ];']
    if data.get("nix_optimize_store"):
        nix_lines += ["  nix.settings.auto-optimise-store = true;"]
    if data.get("nix_gc"):
        nix_lines += [
            "  nix.gc = {",
            "    automatic = true;",
            f'    dates = "{nix_esc(data.get("nix_gc_frequency", "weekly"))}";',
            f'    options = "--delete-older-than {nix_esc(data.get("nix_gc_age", "30d"))}";',
            "  };",
        ]
    if nix_lines or _has_section_brix(brix, "Nix & System"):
        return [_section("Nix & System")] + nix_lines
    return []


def _sec_hardware(data: dict, brix: dict) -> "list[str]":
    hw_lines = []
    if data.get("enable_all_firmware"):
        hw_lines += ["  hardware.enableAllFirmware = true;"]
    cpu_microcode = data.get("cpu_microcode", "none") or "none"
    if cpu_microcode == "intel":
        hw_lines += ["  hardware.cpu.intel.updateMicrocode = true;"]
    elif cpu_microcode == "amd":
        hw_lines += ["  hardware.cpu.amd.updateMicrocode = true;"]
    if data.get("opengl"):
        hw_lines += ["  hardware.opengl.enable = true;"]
        if data.get("opengl_32bit"):
            hw_lines += ["  hardware.opengl.driSupport32Bit = true;"]
    if data.get("zram_swap"):
        hw_lines += ["  zramSwap.enable = true;"]
    if data.get("openrgb"):
        hw_lines += ["  services.hardware.openrgb.enable = true;"]
    if data.get("ledger"):
        hw_lines += ["  hardware.ledger.enable = true;"]
    if data.get("ratbagd"):
        hw_lines += ["  services.ratbagd.enable = true;"]
    if hw_lines or _has_section_brix(brix, "Hardware"):
        return [_section("Hardware")] + hw_lines
    return []


def _sec_virtualisation(data: dict, brix: dict) -> "list[str]":
    virt_lines = []
    if data.get("docker"):
        virt_lines += ["  virtualisation.docker.enable = true;"]
        if data.get("docker_rootless"):
            virt_lines += [
                "  virtualisation.docker.rootless = {",
                "    enable = true;",
                "    setSocketVariable = true;",
                "  };",
            ]
    if data.get("podman"):
        virt_lines += ["  virtualisation.podman.enable = true;"]
        if data.get("podman_docker_compat"):
            virt_lines += ["  virtualisation.podman.dockerCompat = true;"]
    if data.get("virtualbox_host"):
        virt_lines += ["  virtualisation.virtualbox.host.enable = true;"]
    if data.get("virtualbox_guest"):
        virt_lines += ["  virtualisation.virtualbox.guest.enable = true;"]
        if data.get("virtualbox_guest_drag_drop"):
            virt_lines += ["  virtualisation.virtualbox.guest.dragAndDrop = true;"]
    if data.get("libvirtd"):
        virt_lines += ["  virtualisation.libvirtd.enable = true;"]
        if data.get("virt_manager"):
            virt_lines += ["  programs.virt-manager.enable = true;"]
    if virt_lines or _has_section_brix(brix, "Virtualisierung"):
        return [_section("Virtualisierung")] + virt_lines
    return []


def _sec_backup(data: dict, brix: dict) -> "list[str]":
    backup_lines = []
    if data.get("btrfs_scrub"):
        backup_lines += ["  services.btrfs.autoScrub.enable = true;"]
    if data.get("snapper_enable"):
        for sn_cfg in (data.get("snapper_configs") or []):
            if sn_cfg.get("name") and sn_cfg.get("mountpoint"):
                backup_lines += [
                    f"  services.snapper.configs.{nix_attr(sn_cfg['name'])} = {{",
                    f'    SUBVOLUME = "{nix_esc(sn_cfg["mountpoint"])}";',
                    "    TIMELINE_CREATE = true;",
                    "    TIMELINE_CLEANUP = true;",
                    f"    TIMELINE_LIMIT_HOURLY = {sn_cfg.get('hourly', 5)};",
                    f"    TIMELINE_LIMIT_DAILY = {sn_cfg.get('daily', 7)};",
                    f"    TIMELINE_LIMIT_WEEKLY = {sn_cfg.get('weekly', 0)};",
                    f"    TIMELINE_LIMIT_MONTHLY = {sn_cfg.get('monthly', 1)};",
                    f"    TIMELINE_LIMIT_YEARLY = {sn_cfg.get('yearly', 0)};",
                    "  };",
                ]
    if backup_lines or _has_section_brix(brix, "Dateisystem & Backup"):
        return [_section("Dateisystem & Backup")] + backup_lines
    return []


def _sec_home_manager(data: dict, brix: dict) -> "list[str]":
    hm_lines = []
    hm_plasma     = data.get("hm_plasma_manager", False)
    hm_extra_mods = [l.strip() for l in data.get("hm_shared_modules_extra", "").splitlines() if l.strip()]
    hm_shared     = (["plasma-manager.homeModules.plasma-manager"] if hm_plasma else []) + hm_extra_mods
    if hm_shared:
        hm_lines += ["  home-manager.sharedModules = ["]
        for m in hm_shared:
            hm_lines += [f"    {m}"]
        hm_lines += ["  ];"]
    if data.get("hm_use_global_pkgs"):
        hm_lines += ["  home-manager.useGlobalPkgs = true;"]
    if data.get("hm_use_user_packages"):
        hm_lines += ["  home-manager.useUserPackages = true;"]
    if hm_lines or _has_section_brix(brix, "Home Manager"):
        return [_section("Home Manager")] + hm_lines
    return []


def _build_sections(data: dict, brix: dict, *, host_mode: bool) -> "list[str]":
    lines = []
    lines += _sec_boot(data, brix)
    lines += _sec_system(data, host_mode=host_mode)
    lines += _sec_localization(data, brix)
    lines += _sec_network(data, brix, nm_default=not host_mode)
    lines += _sec_services(data, brix)
    lines += _sec_desktop(data, brix)
    lines += _sec_audio(data, brix, gate_32bit=not host_mode)
    lines += _sec_users(data, brix)
    lines += _sec_extra_users(data)
    lines += _sec_programs(data, brix)
    lines += _sec_fonts(data, brix)
    lines += _sec_nix_system(data, brix)
    lines += _sec_hardware(data, brix)
    lines += _sec_virtualisation(data, brix)
    lines += _sec_backup(data, brix)
    lines += _sec_home_manager(data, brix)
    return lines


def _nix_args_of(data: dict) -> str:
    nix_args = (data.get("nix_args") or "config, pkgs, lib").strip()
    if '...' not in nix_args:
        nix_args = nix_args + ', ...'
    return nix_args


def generate_configuration_nix(data: dict) -> str:
    brix = data.get("brick_blocks", {})
    lines = [
        "# Generated by NiCo – NixOS Configurator",
        "# Do not edit manually. Use NiCo or add custom Nix via Nix-Bricks.",
        f"{{ {_nix_args_of(data)} }}: {{",
    ]
    lines += _build_sections(data, brix, host_mode=False)
    lines += [
        "",
        "}",
        "",
    ]
    content = "\n".join(lines)
    if brix:
        content = inject_brick_blocks(content, brix)
    return _add_version_hash(content, ftype="co")


def generate_host_nix(data: dict, host_name: str, hw_config: bool = False) -> str:
    """
    Generate hosts/{host_name}/default.nix from sparse host-specific data.
    Only fields present in data are emitted.
    """
    brix = data.get("brick_blocks", {})
    lines = [
        f"# Host-spezifische Konfiguration für {host_name}",
        "# Generated by NiCo – NixOS Configurator",
        "# Do not edit manually. Use NiCo or add custom Nix via Nix-Bricks.",
        f"{{ {_nix_args_of(data)} }}:",
        "{",
    ]
    lines += _build_sections(data, brix, host_mode=True)
    lines += ["}", ""]
    content = "\n".join(lines)
    if brix:
        content = inject_brick_blocks(content, brix)
    return _add_version_hash(content, ftype="co")


def _home_manager_ref_for_nixpkgs_channel(channel: str) -> str | None:
    if "unstable" in channel:
        return "master"
    m = re.fullmatch(r"nixos-(\d+\.\d+)", channel)
    if m:
        return f"release-{m.group(1)}"
    return None


def generate_flake_nix(data: dict, nixos_dir: "str | Path | None" = None) -> str:
    """Generate flake.nix from panel data.

    nixos_dir: kept for signature compatibility, no longer used for host scanning.
    Host data comes exclusively from data["flake_hosts"].
    """
    hostname    = data.get("hostname", "nixos") or "nixos"
    description = data.get("flake_description") or f"NixOS configuration for {hostname}"
    channel     = data.get("flake_nixpkgs_channel") or "nixos-unstable"
    arch        = data.get("flake_arch") or "x86_64-linux"
    hm_input    = bool(data.get("flake_hm_input"))
    hm_follows  = bool(data.get("flake_hm_follows", True))
    hm_module   = bool(data.get("flake_hm_module", True))
    hw_input    = bool(data.get("flake_nixos_hardware"))
    pm_input    = bool(data.get("flake_plasma_manager"))

    flake_hosts: list[dict] = data.get("flake_hosts") or []
    brix = dict(data.get("flake_brick_blocks", {}))

    # Legacy: if "outputs-declaration" Brix in "Outputs" section exists, the
    # entire outputs block is managed by that Brix.
    has_outputs_declaration = (
        "outputs-declaration" in brix
        and brix["outputs-declaration"].get("section") == "Outputs"
    )

    # ── inputs block ──────────────────────────────────────────────────────────
    inp: list[str] = [f'    nixpkgs.url = "github:NixOS/nixpkgs/{channel}";']
    if hm_input:
        hm_ref = _home_manager_ref_for_nixpkgs_channel(channel)
        hm_url = "github:nix-community/home-manager"
        if hm_ref:
            hm_url = f"{hm_url}/{hm_ref}"
        if hm_follows:
            inp += [
                '    home-manager = {',
                f'      url = "{nix_esc(hm_url)}";',
                '      inputs.nixpkgs.follows = "nixpkgs";',
                '    };',
            ]
        else:
            inp.append(f'    home-manager.url = "{nix_esc(hm_url)}";')
    if hw_input:
        inp.append('    nixos-hardware.url = "github:NixOS/nixos-hardware";')
    if pm_input:
        inp += [
            '    plasma-manager = {',
            '      url = "github:nix-community/plasma-manager";',
            '      inputs.nixpkgs.follows = "nixpkgs";',
            '      inputs.home-manager.follows = "home-manager";',
            '    };',
        ]

    inputs_block = "\n".join(inp)

    # ── build content ─────────────────────────────────────────────────────────
    content = (
        "# Generated by NiCo – NixOS Configurator\n"
        "{\n"
        + _section("Start") + "\n"
        + f'  description = "{nix_esc(description)}";\n'
        + _section("Inputs") + "\n"
        + "  inputs = {\n"
        + f"{inputs_block}\n"
        + _section("Inputs-Extra") + "\n"
        + "  };\n"
    )

    if has_outputs_declaration:
        # Legacy: whole outputs provided by Brix
        content += _section("Outputs") + "\n"
    else:
        # ── outputs args ──────────────────────────────────────────────────────
        out_args: list[str] = ["self", "nixpkgs"]
        if hm_input:
            out_args.append("home-manager")
        if hw_input:
            out_args.append("nixos-hardware")
        if pm_input:
            out_args.append("plasma-manager")
        out_args_str = ", ".join(out_args) + ", ..."

        def _host_header(name: str) -> str:
            dashes = "─" * max(1, _MARKER_WIDTH - len(f"Host: {name}") - 10)
            return f"      # ── Host: {name} {dashes}"

        def _default_host_body(name: str) -> str:
            body = [
                f'      system = "{nix_esc(arch)}";',
                "      modules = [",
                "        ./configuration.nix",
                f"        ./hosts/{name}/hardware-configuration.nix",
                f"        ./hosts/{name}",
            ]
            if hm_input and hm_module:
                body.append("        home-manager.nixosModules.home-manager")
            body += ["      ];"]
            return "\n".join(body)

        def _ensure_host_brix(name: str) -> None:
            section = flake_host_section(name)
            if any(block.get("section") == section for block in brix.values()):
                return
            brick_name = flake_host_brick_name(name)
            suffix = 2
            while brick_name in brix:
                brick_name = f"{flake_host_brick_name(name)}-{suffix}"
                suffix += 1
            brix[brick_name] = {
                "section": section,
                "order": 1,
                "text": format_brick(section, 1, brick_name, _default_host_body(name)),
            }

        def _host_entry(h: dict) -> str:
            hname = h["name"]
            _ensure_host_brix(hname)
            return (
                f"    {hname} = nixpkgs.lib.nixosSystem {{\n"
                + _host_header(hname)
                + "\n"
                + "    };"
            )

        if flake_hosts:
            cfg_block = "\n".join(_host_entry(h) for h in flake_hosts)
        else:
            cfg_block = _host_entry({"name": hostname})

        content += (
            _section("Outputs") + "\n"
            + f"  outputs = {{ {out_args_str} }}: {{\n"
            + "    nixosConfigurations = {\n"
            + _section("Outputs-Hosts") + "\n"
            + f"{cfg_block}\n"
            + "    };\n"
            + _section("Outputs-Extra") + "\n"
            + "  };\n"
        )

    content += "\n}\n"

    if brix:
        content = inject_brick_blocks(content, brix)
    return _add_version_hash(content, ftype="fl")
