"""
Nix file generator.
Produces configuration.nix (and optionally flake.nix) from NiCo's config data.
Section markers use the format  `  # ── SectionName ──…`  so the frontend
can split the preview into collapsible sections that sync with the form.
"""

import hashlib
import re

from .brix import format_brick, inject_brick_blocks
from .importer import flake_host_brick_name, flake_host_section

# Matches nico-version lines in both formats:
#   # nico-version: a3f8c2d1          (legacy / no type)
#   # nico-version: co#a3f8c2d1       (with type code)
_VERSION_RE = re.compile(
    r'^# nico-version: (?:[a-z]+#)?([0-9a-f]{8})\n', re.MULTILINE
)
# Matches only the legacy format (no type prefix) – used to detect missing type
_VERSION_RE_NOTYPE = re.compile(
    r'^# nico-version: ([0-9a-f]{8})\n', re.MULTILINE
)


def _add_version_hash(content: str, ftype: str = "") -> str:
    """Insert '# nico-version: [type#]<hash>' on line 2 of content.
    The hash covers the content *without* the nico-version line itself.
    ftype: optional type code (e.g. 'co', 'fl') prepended as '<ftype>#'.
    """
    h = hashlib.sha256(content.encode()).hexdigest()[:8]
    prefix = f"{ftype}#" if ftype else ""
    lines = content.split("\n")
    lines.insert(1, f"# nico-version: {prefix}{h}")
    return "\n".join(lines)


def check_version_hash(file_content: str) -> str:
    """Check whether a NiCo-generated file has been externally modified.

    Returns:
      'ok'       – hash present and matches
      'modified' – hash present but doesn't match (file was edited outside NiCo)
      'no_hash'  – no nico-version line (file predates this feature or wasn't generated by NiCo)
    """
    m = _VERSION_RE.search(file_content)
    if not m:
        return "no_hash"
    stored = m.group(1)
    # Remove the entire nico-version line (with or without type prefix) to get canonical content
    canonical = _VERSION_RE.sub("", file_content, count=1)
    computed = hashlib.sha256(canonical.encode()).hexdigest()[:8]
    return "ok" if computed == stored else "modified"

# Width of the section marker line (total chars)
_MARKER_WIDTH = 78


def _section(name: str) -> str:
    """Return a section marker line:  # ── Name ──────────────────"""
    dashes = "─" * max(1, _MARKER_WIDTH - len(name) - 6)
    return f"\n  # ── {name} {dashes}"


def _has_section_brix(brix: dict, section: str) -> bool:
    """Return True if any brick block belongs to *section*."""
    return any(b.get("section") == section for b in brix.values())


_DE_SNIPPETS: dict[str, str] = {
    "none": "",
    "gnome": """\
  services.xserver.enable = true;
  services.xserver.displayManager.gdm.enable = true;
  services.xserver.desktopManager.gnome.enable = true;""",
    "kde": """\
  services.xserver.enable = true;
  services.displayManager.sddm.enable = true;
  services.desktopManager.plasma6.enable = true;""",
    "xfce": """\
  services.xserver.enable = true;
  services.xserver.displayManager.lightdm.enable = true;
  services.xserver.desktopManager.xfce.enable = true;""",
    "i3": """\
  services.xserver.enable = true;
  services.xserver.windowManager.i3.enable = true;""",
    "sway":     "  programs.sway.enable = true;",
    "hyprland": "  programs.hyprland.enable = true;",
}


def generate_configuration_nix(data: dict) -> str:
    # ── unpack ────────────────────────────────────────────────────────────
    hostname      = (data.get("hostname")      or "").strip()
    state_version = (data.get("state_version") or "").strip()
    allow_unfree  = data.get("allowUnfree",   False)
    nix_args      = (data.get("nix_args")      or "config, pkgs, lib").strip()
    if '...' not in nix_args:
        nix_args = nix_args + ', ...'

    timezone         = (data.get("timezone")        or "").strip()
    locale           = (data.get("locale")          or "").strip()
    kb_layout        = data.get("keyboard_layout", "")
    kb_variant       = data.get("keyboard_variant","")
    kb_console       = data.get("keyboard_console","")

    networkmanager    = data.get("networkmanager", True)
    ssh               = data.get("ssh",            False)
    fw_disable        = data.get("firewall_disable",  False)
    fw_tcp_enable     = data.get("firewall_tcp_enable", False)
    fw_tcp_raw        = data.get("firewall_tcp_ports", "").strip() if fw_tcp_enable else ""
    fw_tcp            = [p for p in fw_tcp_raw.split() if p.isdigit()]
    fw_udp_enable     = data.get("firewall_udp_enable", False)
    fw_udp_raw        = data.get("firewall_udp_ports", "").strip() if fw_udp_enable else ""
    fw_udp            = [p for p in fw_udp_raw.split() if p.isdigit()]

    printing         = data.get("printing",  False)
    avahi            = data.get("avahi",     False)
    bluetooth        = data.get("bluetooth", False)
    blueman          = data.get("blueman",   False)

    de               = data.get("desktop_environment", "none")
    autologin_user   = data.get("autologin_user", "")

    pipewire         = data.get("pipewire", False)

    username         = data.get("username",              "")
    user_description = data.get("user_description",      "")
    user_password    = data.get("user_initial_password", "")
    user_uid         = data.get("user_uid",              "").strip()
    user_groups_list = data.get("user_groups",           ["wheel", "networkmanager"])
    user_groups_extra_raw = data.get("user_groups_extra", "").strip()
    user_groups_extra = [g for g in user_groups_extra_raw.split() if g]
    user_all_groups  = sorted(set(user_groups_list + user_groups_extra)) or ["wheel"]
    user_shell       = data.get("user_shell",            "bash")
    user_extra_nix   = data.get("user_extra_nix",        "").strip()

    extra_users      = data.get("extra_users", [])

    packages         = sorted(
        (p["attr"] for p in data.get("packages", []) if p.get("enabled", True))
    )

    flakes           = data.get("flakes",             False)
    nix_optimize     = data.get("nix_optimize_store", False)
    nix_gc           = data.get("nix_gc",             False)
    nix_gc_freq      = data.get("nix_gc_frequency",   "weekly")
    nix_gc_age       = data.get("nix_gc_age",         "30d")

    # Collect font package attrs (checkboxes + free-text field)
    fonts_checked    = data.get("fonts", [])
    fonts_extra_raw  = data.get("fonts_extra", "").strip()
    fonts_extra      = [l.strip() for l in fonts_extra_raw.splitlines() if l.strip()]
    fonts_all        = sorted(set(fonts_checked + fonts_extra))

    brix             = data.get("brick_blocks", {})
    # ── build ──────────────────────────────────────────────────────────────
    lines = [
        "# Generated by NiCo – NixOS Configurator",
        "# Do not edit manually. Use NiCo or add custom Nix via Nix-Bricks.",
        f"{{ {nix_args} }}: {{",
    ]

    # ── Boot ──────────────────────────────────────────────────────────────
    boot_loader        = data.get("boot_loader",         "none")
    boot_efi_can_touch = data.get("boot_efi_can_touch",  False)
    boot_efi_mount     = (data.get("boot_efi_mount_point", "/boot") or "/boot").strip()
    boot_config_limit  = int(data.get("boot_config_limit",  5) or 5)

    if boot_loader != "none" or _has_section_brix(brix, "Boot"):
        lines += [_section("Boot")]
        if boot_loader != "none":
            if boot_loader == "systemd-boot":
                lines += [
                    "  boot.loader.systemd-boot.enable = true;",
                    f"  boot.loader.systemd-boot.configurationLimit = {boot_config_limit};",
                ]
            elif boot_loader == "grub":
                lines += ["  boot.loader.grub.enable = true;"]
            lines += [f'  boot.loader.efi.canTouchEfiVariables = {"true" if boot_efi_can_touch else "false"};']
            if boot_efi_mount != "/boot":
                lines += [f'  boot.loader.efi.efiSysMountPoint = "{boot_efi_mount}";']

    # ── System ────────────────────────────────────────────────────────────
    lines += [_section("System")]
    if hostname:
        lines += [f'  networking.hostName = "{hostname}";']
    lines += [
        f'  system.stateVersion = "{state_version}";' if state_version
        else '  # system.stateVersion = "";  # TODO: set NixOS state version'
    ]

    # ── Lokalisierung ──────────────────────────────────────────────────────
    extra_locale = data.get("extra_locale", "")
    loc_lines = []
    if timezone:
        loc_lines += [f'  time.timeZone = "{timezone}";', ""]
    if locale:
        loc_lines += [f'  i18n.defaultLocale = "{locale}";']
    if extra_locale:
        loc_lines += [
            "  i18n.extraLocaleSettings = {",
            f'    LC_ADDRESS        = "{extra_locale}";',
            f'    LC_IDENTIFICATION = "{extra_locale}";',
            f'    LC_MEASUREMENT    = "{extra_locale}";',
            f'    LC_MONETARY       = "{extra_locale}";',
            f'    LC_NAME           = "{extra_locale}";',
            f'    LC_NUMERIC        = "{extra_locale}";',
            f'    LC_PAPER          = "{extra_locale}";',
            f'    LC_TELEPHONE      = "{extra_locale}";',
            f'    LC_TIME           = "{extra_locale}";',
            "  };",
        ]
    if kb_layout:
        loc_lines += [
            "",
            "  services.xserver.xkb = {",
            f'    layout = "{kb_layout}";',
            f'    variant = "{kb_variant}";',
            "  };",
        ]
    if kb_console:
        loc_lines += [f'  console.keyMap = "{kb_console}";']
    if loc_lines or _has_section_brix(brix, "Lokalisierung"):
        lines += [_section("Lokalisierung")] + loc_lines

    # ── Netzwerk ───────────────────────────────────────────────────────────
    fw_has_content = fw_disable or fw_tcp or fw_udp
    if networkmanager or ssh or fw_has_content or _has_section_brix(brix, "Netzwerk"):
        lines += [_section("Netzwerk")]
        if networkmanager:
            lines += ["  networking.networkmanager.enable = true;"]
        if ssh:
            lines += ["  services.openssh.enable = true;"]
        if fw_disable:
            lines += ["  networking.firewall.enable = false;"]
        if fw_tcp:
            lines += [f"  networking.firewall.allowedTCPPorts = [ {' '.join(fw_tcp)} ];"]
        if fw_udp:
            lines += [f"  networking.firewall.allowedUDPPorts = [ {' '.join(fw_udp)} ];"]

    # ── Services ───────────────────────────────────────────────────────────
    _svc_header_added = False
    if printing or avahi or bluetooth or _has_section_brix(brix, "Services"):
        lines += [_section("Services")]
        _svc_header_added = True
        if printing:
            lines += ["  services.printing.enable = true;"]
        if avahi:
            lines += [
                "  services.avahi = {",
                "    enable = true;",
                "    nssmdns4 = true;",
                "    openFirewall = true;",
                "  };",
            ]
        if bluetooth:
            lines += ["  hardware.bluetooth.enable = true;"]
            if blueman:
                lines += ["  services.blueman.enable = true;"]

    libinput  = data.get("libinput",  False)
    fprintd   = data.get("fprintd",   False)
    pcscd     = data.get("pcscd",     False)
    sunshine  = data.get("sunshine",  False)
    svc2_lines = []
    if libinput:
        svc2_lines += ["  services.libinput.enable = true;"]
    if fprintd:
        svc2_lines += ["  services.fprintd.enable = true;"]
    if pcscd:
        svc2_lines += ["  services.pcscd.enable = true;"]
    if sunshine:
        svc2_lines += ["  services.sunshine.enable = true;"]
    if svc2_lines:
        if not _svc_header_added:
            lines += [_section("Services")]
        lines += svc2_lines

    # ── Desktop ────────────────────────────────────────────────────────────
    de_snippet = _DE_SNIPPETS.get(de, "")
    if de_snippet or autologin_user or _has_section_brix(brix, "Desktop"):
        lines += [_section("Desktop")]
        if de_snippet:
            lines += [de_snippet]
        if autologin_user:
            lines += [
                "  services.displayManager.autoLogin = {",
                "    enable = true;",
                f'    user = "{autologin_user}";',
                "  };",
            ]

    # ── Audio ──────────────────────────────────────────────────────────────
    pipewire_32bit   = data.get("pipewire_32bit", False)
    if pipewire or _has_section_brix(brix, "Audio"):
        lines += [_section("Audio")]
        if pipewire:
            lines += [
                "  services.pulseaudio.enable = false;",
                "  security.rtkit.enable = true;",
                "  services.pipewire = {",
                "    enable = true;",
                "    alsa.enable = true;",
                "    pulse.enable = true;",
                "  };",
            ]
            if pipewire_32bit:
                lines += ["  services.pipewire.alsa.support32Bit = true;"]

    # ── Benutzer ───────────────────────────────────────────────────────────
    if username:
        groups_str = " ".join(f'"{g}"' for g in user_all_groups)
        lines += [
            _section("Benutzer"),
            f"  users.users.{username} = {{",
            "    isNormalUser = true;",
        ]
        if user_description:
            lines += [f'    description = "{user_description}";']
        if user_uid:
            lines += [f"    uid = {user_uid};"]
        if user_password:
            lines += [f'    initialPassword = "{user_password}";']
        lines += [f"    extraGroups = [ {groups_str} ];"]
        if user_shell != "bash":
            shell_pkg = {"zsh": "zsh", "fish": "fish", "nushell": "nushell"}.get(user_shell, user_shell)
            lines += [f"    shell = pkgs.{shell_pkg};"]
        if user_extra_nix:
            for ln in user_extra_nix.splitlines():
                if ln.strip():
                    lines += [f"    {ln.strip()}"]
        lines += ["  };"]

        # Guest user block (no password, no sudo)
        if data.get("guest_user", False):
            lines += [
                '  users.users.gast = {',
                '    isNormalUser = true;',
                '    initialPassword = "";',
                '  };',
            ]
    elif _has_section_brix(brix, "Benutzer"):
        lines += [_section("Benutzer")]

    # ── Weitere Benutzer ───────────────────────────────────────────────────
    for eu in extra_users:
        eu_name = (eu.get("username") or "").strip()
        if not eu_name:
            continue
        eu_desc   = (eu.get("description") or "").strip()
        eu_pass   = (eu.get("initial_password") or "").strip()
        eu_uid    = str(eu.get("uid") or "").strip()
        eu_groups = eu.get("groups") or ["wheel", "networkmanager"]
        eu_shell  = (eu.get("shell") or "bash").strip()
        eu_extra  = (eu.get("extra_nix") or "").strip()
        eu_groups_str = " ".join(f'"{g}"' for g in eu_groups)
        lines += [f"  users.users.{eu_name} = {{", "    isNormalUser = true;"]
        if eu_desc:
            lines += [f'    description = "{eu_desc}";']
        if eu_uid:
            lines += [f"    uid = {eu_uid};"]
        if eu_pass:
            lines += [f'    initialPassword = "{eu_pass}";']
        lines += [f"    extraGroups = [ {eu_groups_str} ];"]
        if eu_shell != "bash":
            shell_pkg = {"zsh": "zsh", "fish": "fish", "nushell": "nushell"}.get(eu_shell, eu_shell)
            lines += [f"    shell = pkgs.{shell_pkg};"]
        if eu_extra:
            for ln in eu_extra.splitlines():
                if ln.strip():
                    lines += [f"    {ln.strip()}"]
        lines += ["  };"]

    # ── Programme ──────────────────────────────────────────────────────────
    steam    = data.get("steam",    False)
    appimage = data.get("appimage", False)
    firefox  = data.get("firefox",  False)
    prog_lines = []
    if allow_unfree:
        prog_lines += ["  nixpkgs.config.allowUnfree = true;"]
    if steam:
        prog_lines += ["  programs.steam.enable = true;"]
    if appimage:
        prog_lines += [
            "  programs.appimage = {",
            "    enable = true;",
            "    binfmt = true;",
            "  };",
        ]
    if firefox:
        ff_lang  = data.get("firefox_lang_packs", "")
        ff_prefs = data.get("firefox_prefs", "")
        lang_list = [p.strip() for p in ff_lang.split(",") if p.strip()] if ff_lang else []
        pref_lines = [l.strip() for l in ff_prefs.splitlines() if l.strip()] if ff_prefs else []
        if lang_list or pref_lines:
            prog_lines += ["  programs.firefox = {", "    enable = true;"]
            if lang_list:
                packs = " ".join(f'"{p}"' for p in lang_list)
                prog_lines += [f"    languagePacks = [ {packs} ];"]
            if pref_lines:
                prog_lines += ["    preferences = {"]
                for pl in pref_lines:
                    prog_lines += [f"      {pl}"]
                prog_lines += ["    };"]
            prog_lines += ["  };"]
        else:
            prog_lines += ["  programs.firefox.enable = true;"]
    if packages:
        pkg_lines = "\n".join(f"    {attr}" for attr in packages)
        prog_lines += [
            "  environment.systemPackages = with pkgs; [",
            pkg_lines,
            "  ];",
        ]
    if prog_lines or _has_section_brix(brix, "Programme"):
        lines += [_section("Programme")] + prog_lines

    # ── Schriftarten ──────────────────────────────────────────────────────
    if fonts_all:
        font_lines = "\n".join(f"    {f}" for f in fonts_all)
        lines += [
            _section("Schriftarten"),
            "  fonts.packages = with pkgs; [",
            font_lines,
            "  ];",
        ]
    elif _has_section_brix(brix, "Schriftarten"):
        lines += [_section("Schriftarten")]

    # ── Nix & System ──────────────────────────────────────────────────────
    nix_lines = []
    if user_shell in ("zsh", "fish"):
        nix_lines += [f"  programs.{user_shell}.enable = true;"]
    if flakes:
        nix_lines += ['  nix.settings.experimental-features = [ "nix-command" "flakes" ];']
    if nix_optimize:
        nix_lines += ["  nix.settings.auto-optimise-store = true;"]
    if nix_gc:
        nix_lines += [
            "  nix.gc = {",
            "    automatic = true;",
            f'    dates = "{nix_gc_freq}";',
            f'    options = "--delete-older-than {nix_gc_age}";',
            "  };",
        ]
    if nix_lines or _has_section_brix(brix, "Nix & System"):
        lines += [_section("Nix & System")] + nix_lines

    # ── Hardware ──────────────────────────────────────────────────────────────
    enable_all_firmware = data.get("enable_all_firmware", False)
    cpu_microcode       = data.get("cpu_microcode",       "none")
    opengl              = data.get("opengl",              False)
    opengl_32bit        = data.get("opengl_32bit",        False)
    zram_swap           = data.get("zram_swap",           False)

    hw_lines = []
    if enable_all_firmware:
        hw_lines += ["  hardware.enableAllFirmware = true;"]
    if cpu_microcode == "intel":
        hw_lines += ["  hardware.cpu.intel.updateMicrocode = true;"]
    elif cpu_microcode == "amd":
        hw_lines += ["  hardware.cpu.amd.updateMicrocode = true;"]
    if opengl:
        hw_lines += ["  hardware.opengl.enable = true;"]
        if opengl_32bit:
            hw_lines += ["  hardware.opengl.driSupport32Bit = true;"]
    if zram_swap:
        hw_lines += ["  zramSwap.enable = true;"]
    openrgb  = data.get("openrgb",  False)
    ledger   = data.get("ledger",   False)
    ratbagd  = data.get("ratbagd",  False)
    if openrgb:
        hw_lines += ["  services.hardware.openrgb.enable = true;"]
    if ledger:
        hw_lines += ["  hardware.ledger.enable = true;"]
    if ratbagd:
        hw_lines += ["  services.ratbagd.enable = true;"]
    if hw_lines or _has_section_brix(brix, "Hardware"):
        lines += [_section("Hardware")] + hw_lines

    # ── Virtualisierung ───────────────────────────────────────────────────────
    docker               = data.get("docker",               False)
    docker_rootless      = data.get("docker_rootless",      False)
    podman               = data.get("podman",               False)
    podman_docker_compat = data.get("podman_docker_compat", False)
    virtualbox_host      = data.get("virtualbox_host",      False)
    libvirtd             = data.get("libvirtd",             False)
    virt_manager         = data.get("virt_manager",         False)

    virt_lines = []
    if docker:
        virt_lines += ["  virtualisation.docker.enable = true;"]
        if docker_rootless:
            virt_lines += [
                "  virtualisation.docker.rootless = {",
                "    enable = true;",
                "    setSocketVariable = true;",
                "  };",
            ]
    if podman:
        virt_lines += ["  virtualisation.podman.enable = true;"]
        if podman_docker_compat:
            virt_lines += ["  virtualisation.podman.dockerCompat = true;"]
    if virtualbox_host:
        virt_lines += ["  virtualisation.virtualbox.host.enable = true;"]
    virtualbox_guest     = data.get("virtualbox_guest",          False)
    virtualbox_guest_dnd = data.get("virtualbox_guest_drag_drop", False)
    if virtualbox_guest:
        virt_lines += ["  virtualisation.virtualbox.guest.enable = true;"]
        if virtualbox_guest_dnd:
            virt_lines += ["  virtualisation.virtualbox.guest.dragAndDrop = true;"]
    if libvirtd:
        virt_lines += ["  virtualisation.libvirtd.enable = true;"]
        if virt_manager:
            virt_lines += ["  programs.virt-manager.enable = true;"]
    if virt_lines or _has_section_brix(brix, "Virtualisierung"):
        lines += [_section("Virtualisierung")] + virt_lines

    # ── Dateisystem & Backup ──────────────────────────────────────────────────
    btrfs_scrub  = data.get("btrfs_scrub",  False)
    snapper_home = data.get("snapper_home", False)
    snapper_root = data.get("snapper_root", False)
    sn_hourly    = data.get("snapper_timeline_hourly",  5)
    sn_daily     = data.get("snapper_timeline_daily",   7)
    sn_weekly    = data.get("snapper_timeline_weekly",  0)
    sn_monthly   = data.get("snapper_timeline_monthly", 1)
    sn_yearly    = data.get("snapper_timeline_yearly",  0)

    def _snapper_cfg(cfg_name: str, subvol: str) -> list[str]:
        return [
            f"  services.snapper.configs.{cfg_name} = {{",
            f'    SUBVOLUME = "{subvol}";',
            "    TIMELINE_CREATE = true;",
            "    TIMELINE_CLEANUP = true;",
            f"    TIMELINE_LIMIT_HOURLY = {sn_hourly};",
            f"    TIMELINE_LIMIT_DAILY = {sn_daily};",
            f"    TIMELINE_LIMIT_WEEKLY = {sn_weekly};",
            f"    TIMELINE_LIMIT_MONTHLY = {sn_monthly};",
            f"    TIMELINE_LIMIT_YEARLY = {sn_yearly};",
            "  };",
        ]

    backup_lines = []
    if btrfs_scrub:
        backup_lines += ["  services.btrfs.autoScrub.enable = true;"]
    if snapper_home:
        backup_lines += _snapper_cfg("home", "/home")
    if snapper_root:
        backup_lines += _snapper_cfg("root", "/")
    if backup_lines or _has_section_brix(brix, "Dateisystem & Backup"):
        lines += [_section("Dateisystem & Backup")] + backup_lines

    # ── Home Manager NixOS-Modul ──────────────────────────────────────────
    hm_use_global  = data.get("hm_use_global_pkgs",    False)
    hm_use_user    = data.get("hm_use_user_packages",  False)
    hm_plasma      = data.get("hm_plasma_manager",     False)
    hm_extra_raw   = data.get("hm_shared_modules_extra", "")
    hm_extra_mods  = [l.strip() for l in hm_extra_raw.splitlines() if l.strip()]
    hm_shared_mods = (["plasma-manager.homeModules.plasma-manager"] if hm_plasma else []) + hm_extra_mods

    if hm_use_global or hm_use_user or hm_shared_mods or _has_section_brix(brix, "Home Manager"):
        lines += [_section("Home Manager")]
        if hm_shared_mods:
            lines += ["  home-manager.sharedModules = ["]
            for m in hm_shared_mods:
                lines += [f"    {m}"]
            lines += ["  ];"]
        if hm_use_global:
            lines += ["  home-manager.useGlobalPkgs = true;"]
        if hm_use_user:
            lines += ["  home-manager.useUserPackages = true;"]

    lines += [
        "",
        "}",
        "",
    ]

    content = "\n".join(lines)
    if brix:
        content = inject_brick_blocks(content, brix)
    return _add_version_hash(content, ftype="co")


def generate_host_nix(data: dict, host_name: str, hw_config: bool = False) -> str:
    """
    Generate hosts/{host_name}/default.nix from sparse host-specific data.
    Only fields present in data are emitted.
    """
    brix = data.get("brick_blocks", {})

    nix_args = (data.get("nix_args") or "config, pkgs, lib").strip()
    if '...' not in nix_args:
        nix_args = nix_args + ', ...'
    lines = [
        f"# Host-spezifische Konfiguration für {host_name}",
        "# Generated by NiCo – NixOS Configurator",
        "# Do not edit manually. Use NiCo or add custom Nix via Nix-Bricks.",
        f"{{ {nix_args} }}:",
        "{",
    ]

    # Boot
    boot_loader = data.get("boot_loader", "none") or "none"
    if boot_loader != "none" or _has_section_brix(brix, "Boot"):
        boot_efi_can_touch = data.get("boot_efi_can_touch", False)
        boot_efi_mount = (data.get("boot_efi_mount_point", "/boot") or "/boot").strip()
        boot_config_limit = int(data.get("boot_config_limit", 5) or 5)
        lines += [_section("Boot")]
        if boot_loader != "none":
            if boot_loader == "systemd-boot":
                lines += [
                    "  boot.loader.systemd-boot.enable = true;",
                    f"  boot.loader.systemd-boot.configurationLimit = {boot_config_limit};",
                ]
            elif boot_loader == "grub":
                lines += ["  boot.loader.grub.enable = true;"]
            lines += [f'  boot.loader.efi.canTouchEfiVariables = {"true" if boot_efi_can_touch else "false"};']
            if boot_efi_mount != "/boot":
                lines += [f'  boot.loader.efi.efiSysMountPoint = "{boot_efi_mount}";']

    # System
    sys_lines = []
    hostname = data.get("hostname", "")
    if hostname:
        sys_lines += [f'  networking.hostName = "{hostname}";']
    if sys_lines:
        lines += [_section("System")] + sys_lines

    # Lokalisierung
    loc_lines = []
    if data.get("timezone"):
        loc_lines += [f'  time.timeZone = "{data["timezone"]}";', ""]
    if data.get("locale"):
        loc_lines += [f'  i18n.defaultLocale = "{data["locale"]}";']
    extra_locale = data.get("extra_locale", "")
    if extra_locale:
        loc_lines += [
            "  i18n.extraLocaleSettings = {",
            f'    LC_ADDRESS        = "{extra_locale}";',
            f'    LC_IDENTIFICATION = "{extra_locale}";',
            f'    LC_MEASUREMENT    = "{extra_locale}";',
            f'    LC_MONETARY       = "{extra_locale}";',
            f'    LC_NAME           = "{extra_locale}";',
            f'    LC_NUMERIC        = "{extra_locale}";',
            f'    LC_PAPER          = "{extra_locale}";',
            f'    LC_TELEPHONE      = "{extra_locale}";',
            f'    LC_TIME           = "{extra_locale}";',
            "  };",
        ]
    kb_layout = data.get("keyboard_layout", "")
    if kb_layout:
        loc_lines += [
            "",
            "  services.xserver.xkb = {",
            f'    layout = "{kb_layout}";',
            f'    variant = "{data.get("keyboard_variant", "")}";',
            "  };",
        ]
    if data.get("keyboard_console"):
        loc_lines += [f'  console.keyMap = "{data["keyboard_console"]}";']
    if loc_lines or _has_section_brix(brix, "Lokalisierung"):
        lines += [_section("Lokalisierung")] + loc_lines

    # Netzwerk
    net_lines = []
    if data.get("networkmanager"):
        net_lines += ["  networking.networkmanager.enable = true;"]
    if data.get("ssh"):
        net_lines += ["  services.openssh.enable = true;"]
    if data.get("firewall_disable"):
        net_lines += ["  networking.firewall.enable = false;"]
    if data.get("firewall_tcp_enable"):
        fw_tcp_raw = (data.get("firewall_tcp_ports") or "").strip()
        fw_tcp = [p for p in fw_tcp_raw.split() if p.isdigit()]
        if fw_tcp:
            net_lines += [f"  networking.firewall.allowedTCPPorts = [ {' '.join(fw_tcp)} ];"]
    if data.get("firewall_udp_enable"):
        fw_udp_raw = (data.get("firewall_udp_ports") or "").strip()
        fw_udp = [p for p in fw_udp_raw.split() if p.isdigit()]
        if fw_udp:
            net_lines += [f"  networking.firewall.allowedUDPPorts = [ {' '.join(fw_udp)} ];"]
    if net_lines or _has_section_brix(brix, "Netzwerk"):
        lines += [_section("Netzwerk")] + net_lines

    # Services
    svc_lines = []
    if data.get("printing"):
        svc_lines += ["  services.printing.enable = true;"]
    if data.get("avahi"):
        svc_lines += [
            "  services.avahi = {",
            "    enable = true;",
            "    nssmdns4 = true;",
            "    openFirewall = true;",
            "  };",
        ]
    if data.get("bluetooth"):
        svc_lines += ["  hardware.bluetooth.enable = true;"]
        if data.get("blueman"):
            svc_lines += ["  services.blueman.enable = true;"]
    if data.get("libinput"):
        svc_lines += ["  services.libinput.enable = true;"]
    if data.get("fprintd"):
        svc_lines += ["  services.fprintd.enable = true;"]
    if data.get("pcscd"):
        svc_lines += ["  services.pcscd.enable = true;"]
    if data.get("sunshine"):
        svc_lines += ["  services.sunshine.enable = true;"]
    if svc_lines or _has_section_brix(brix, "Services"):
        lines += [_section("Services")] + svc_lines

    # Desktop
    de = data.get("desktop_environment", "none") or "none"
    de_snippet = _DE_SNIPPETS.get(de, "")
    autologin_user = data.get("autologin_user", "")
    if de_snippet or autologin_user or _has_section_brix(brix, "Desktop"):
        lines += [_section("Desktop")]
        if de_snippet:
            lines += [de_snippet]
        if autologin_user:
            lines += [
                "  services.displayManager.autoLogin = {",
                "    enable = true;",
                f'    user = "{autologin_user}";',
                "  };",
            ]

    # Audio
    audio_lines = []
    if data.get("pipewire"):
        audio_lines += [
            "  services.pulseaudio.enable = false;",
            "  security.rtkit.enable = true;",
            "  services.pipewire = {",
            "    enable = true;",
            "    alsa.enable = true;",
            "    pulse.enable = true;",
            "  };",
        ]
    if data.get("pipewire_32bit"):
        audio_lines += ["  services.pipewire.alsa.support32Bit = true;"]
    if audio_lines or _has_section_brix(brix, "Audio"):
        lines += [_section("Audio")] + audio_lines

    # Benutzer
    username = data.get("username", "")
    if username:
        user_groups_list = data.get("user_groups", ["wheel", "networkmanager"])
        user_groups_extra_raw = (data.get("user_groups_extra") or "").strip()
        user_groups_extra = [g for g in user_groups_extra_raw.split() if g]
        user_all_groups = sorted(set(user_groups_list + user_groups_extra)) or ["wheel"]
        groups_str = " ".join(f'"{g}"' for g in user_all_groups)
        user_shell = data.get("user_shell", "bash") or "bash"
        lines += [
            _section("Benutzer"),
            f"  users.users.{username} = {{",
            "    isNormalUser = true;",
        ]
        if data.get("user_description"):
            lines += [f'    description = "{data["user_description"]}";']
        if (data.get("user_uid") or "").strip():
            lines += [f"    uid = {data['user_uid'].strip()};"]
        if data.get("user_initial_password"):
            lines += [f'    initialPassword = "{data["user_initial_password"]}";']
        lines += [f"    extraGroups = [ {groups_str} ];"]
        if user_shell != "bash":
            shell_pkg = {"zsh": "zsh", "fish": "fish", "nushell": "nushell"}.get(user_shell, user_shell)
            lines += [f"    shell = pkgs.{shell_pkg};"]
        user_extra_nix = (data.get("user_extra_nix") or "").strip()
        for ln in user_extra_nix.splitlines():
            if ln.strip():
                lines += [f"    {ln.strip()}"]
        lines += ["  };"]
        if data.get("guest_user"):
            lines += [
                "  users.users.gast = {",
                "    isNormalUser = true;",
                '    initialPassword = "";',
                "  };",
            ]
    elif _has_section_brix(brix, "Benutzer"):
        lines += [_section("Benutzer")]

    # Weitere Benutzer
    for eu in data.get("extra_users", []):
        eu_name = (eu.get("username") or "").strip()
        if not eu_name:
            continue
        eu_desc   = (eu.get("description") or "").strip()
        eu_pass   = (eu.get("initial_password") or "").strip()
        eu_uid    = str(eu.get("uid") or "").strip()
        eu_groups = eu.get("groups") or ["wheel", "networkmanager"]
        eu_shell  = (eu.get("shell") or "bash").strip()
        eu_extra  = (eu.get("extra_nix") or "").strip()
        eu_groups_str = " ".join(f'"{g}"' for g in eu_groups)
        lines += [f"  users.users.{eu_name} = {{", "    isNormalUser = true;"]
        if eu_desc:
            lines += [f'    description = "{eu_desc}";']
        if eu_uid:
            lines += [f"    uid = {eu_uid};"]
        if eu_pass:
            lines += [f'    initialPassword = "{eu_pass}";']
        lines += [f"    extraGroups = [ {eu_groups_str} ];"]
        if eu_shell != "bash":
            shell_pkg = {"zsh": "zsh", "fish": "fish", "nushell": "nushell"}.get(eu_shell, eu_shell)
            lines += [f"    shell = pkgs.{shell_pkg};"]
        if eu_extra:
            for ln in eu_extra.splitlines():
                if ln.strip():
                    lines += [f"    {ln.strip()}"]
        lines += ["  };"]

    # Programme
    packages = sorted(p["attr"] for p in data.get("packages", []) if p.get("enabled", True))
    prog_lines = []
    if data.get("allowUnfree"):
        prog_lines += ["  nixpkgs.config.allowUnfree = true;"]
    if data.get("steam"):
        prog_lines += ["  programs.steam.enable = true;"]
    if data.get("appimage"):
        prog_lines += ["  programs.appimage = {", "    enable = true;", "    binfmt = true;", "  };"]
    if data.get("firefox"):
        ff_lang = data.get("firefox_lang_packs", "")
        ff_prefs = data.get("firefox_prefs", "")
        lang_list = [p.strip() for p in ff_lang.split(",") if p.strip()] if ff_lang else []
        pref_lines_raw = [l.strip() for l in ff_prefs.splitlines() if l.strip()] if ff_prefs else []
        if lang_list or pref_lines_raw:
            prog_lines += ["  programs.firefox = {", "    enable = true;"]
            if lang_list:
                prog_lines += [f"    languagePacks = [ {' '.join(f'\"' + p + '\"' for p in lang_list)} ];"]
            if pref_lines_raw:
                prog_lines += ["    preferences = {"]
                for pl in pref_lines_raw:
                    prog_lines += [f"      {pl}"]
                prog_lines += ["    };"]
            prog_lines += ["  };"]
        else:
            prog_lines += ["  programs.firefox.enable = true;"]
    if packages:
        pkg_lines = "\n".join(f"    {attr}" for attr in packages)
        prog_lines += [
            "  environment.systemPackages = with pkgs; [",
            pkg_lines,
            "  ];",
        ]
    if prog_lines or _has_section_brix(brix, "Programme"):
        lines += [_section("Programme")] + prog_lines

    # Schriftarten (host-specific)
    fonts_checked = data.get("fonts", [])
    fonts_extra_raw = (data.get("fonts_extra") or "").strip()
    fonts_extra = [l.strip() for l in fonts_extra_raw.splitlines() if l.strip()]
    fonts_all = sorted(set(fonts_checked + fonts_extra))
    if fonts_all:
        lines += [
            _section("Schriftarten"),
            "  fonts.packages = with pkgs; [",
            *[f"    {f}" for f in fonts_all],
            "  ];",
        ]
    elif _has_section_brix(brix, "Schriftarten"):
        lines += [_section("Schriftarten")]

    # Nix & System
    nix_lines = []
    user_shell = data.get("user_shell", "bash") or "bash"
    if user_shell in ("zsh", "fish"):
        nix_lines += [f"  programs.{user_shell}.enable = true;"]
    if data.get("flakes"):
        nix_lines += ['  nix.settings.experimental-features = [ "nix-command" "flakes" ];']
    if data.get("nix_optimize_store"):
        nix_lines += ["  nix.settings.auto-optimise-store = true;"]
    if data.get("nix_gc"):
        nix_lines += [
            "  nix.gc = {",
            "    automatic = true;",
            f'    dates = "{data.get("nix_gc_frequency", "weekly")}";',
            f'    options = "--delete-older-than {data.get("nix_gc_age", "30d")}";',
            "  };",
        ]
    if nix_lines or _has_section_brix(brix, "Nix & System"):
        lines += [_section("Nix & System")] + nix_lines

    # Hardware
    hw_lines = []
    if data.get("enable_all_firmware"):
        hw_lines += ["  hardware.enableAllFirmware = true;"]
    cpu_microcode = data.get("cpu_microcode", "none") or "none"
    if cpu_microcode == "intel":
        hw_lines += ["  hardware.cpu.intel.updateMicrocode = true;"]
    elif cpu_microcode == "amd":
        hw_lines += ["  hardware.cpu.amd.updateMicrocode = true;"]
    if data.get("opengl"):
        hw_lines += ["  hardware.opengl.enable = true;"]
        if data.get("opengl_32bit"):
            hw_lines += ["  hardware.opengl.driSupport32Bit = true;"]
    if data.get("zram_swap"):
        hw_lines += ["  zramSwap.enable = true;"]
    if data.get("openrgb"):
        hw_lines += ["  services.hardware.openrgb.enable = true;"]
    if data.get("ledger"):
        hw_lines += ["  hardware.ledger.enable = true;"]
    if data.get("ratbagd"):
        hw_lines += ["  services.ratbagd.enable = true;"]
    if hw_lines or _has_section_brix(brix, "Hardware"):
        lines += [_section("Hardware")] + hw_lines

    # Virtualisierung
    virt_lines = []
    if data.get("docker"):
        virt_lines += ["  virtualisation.docker.enable = true;"]
        if data.get("docker_rootless"):
            virt_lines += [
                "  virtualisation.docker.rootless = {",
                "    enable = true;",
                "    setSocketVariable = true;",
                "  };",
            ]
    if data.get("podman"):
        virt_lines += ["  virtualisation.podman.enable = true;"]
        if data.get("podman_docker_compat"):
            virt_lines += ["  virtualisation.podman.dockerCompat = true;"]
    if data.get("virtualbox_host"):
        virt_lines += ["  virtualisation.virtualbox.host.enable = true;"]
    if data.get("virtualbox_guest"):
        virt_lines += ["  virtualisation.virtualbox.guest.enable = true;"]
        if data.get("virtualbox_guest_drag_drop"):
            virt_lines += ["  virtualisation.virtualbox.guest.dragAndDrop = true;"]
    if data.get("libvirtd"):
        virt_lines += ["  virtualisation.libvirtd.enable = true;"]
        if data.get("virt_manager"):
            virt_lines += ["  programs.virt-manager.enable = true;"]
    if virt_lines or _has_section_brix(brix, "Virtualisierung"):
        lines += [_section("Virtualisierung")] + virt_lines

    # Dateisystem & Backup
    backup_lines = []
    if data.get("btrfs_scrub"):
        backup_lines += ["  services.btrfs.autoScrub.enable = true;"]
    sn_hourly  = data.get("snapper_timeline_hourly",  5)
    sn_daily   = data.get("snapper_timeline_daily",   7)
    sn_weekly  = data.get("snapper_timeline_weekly",  0)
    sn_monthly = data.get("snapper_timeline_monthly", 1)
    sn_yearly  = data.get("snapper_timeline_yearly",  0)
    def _sn(cfg, subvol):
        return [
            f"  services.snapper.configs.{cfg} = {{",
            f'    SUBVOLUME = "{subvol}";',
            "    TIMELINE_CREATE = true;",
            "    TIMELINE_CLEANUP = true;",
            f"    TIMELINE_LIMIT_HOURLY = {sn_hourly};",
            f"    TIMELINE_LIMIT_DAILY = {sn_daily};",
            f"    TIMELINE_LIMIT_WEEKLY = {sn_weekly};",
            f"    TIMELINE_LIMIT_MONTHLY = {sn_monthly};",
            f"    TIMELINE_LIMIT_YEARLY = {sn_yearly};",
            "  };",
        ]
    if data.get("snapper_home"):
        backup_lines += _sn("home", "/home")
    if data.get("snapper_root"):
        backup_lines += _sn("root", "/")
    if backup_lines or _has_section_brix(brix, "Dateisystem & Backup"):
        lines += [_section("Dateisystem & Backup")] + backup_lines

    # Home Manager NixOS-Modul
    hm_lines = []
    hm_plasma = data.get("hm_plasma_manager", False)
    hm_extra_raw = data.get("hm_shared_modules_extra", "")
    hm_extra_mods = [l.strip() for l in hm_extra_raw.splitlines() if l.strip()]
    hm_shared = (["plasma-manager.homeModules.plasma-manager"] if hm_plasma else []) + hm_extra_mods
    if hm_shared:
        hm_lines += ["  home-manager.sharedModules = [", *[f"    {m}" for m in hm_shared], "  ];"]
    if data.get("hm_use_global_pkgs"):
        hm_lines += ["  home-manager.useGlobalPkgs = true;"]
    if data.get("hm_use_user_packages"):
        hm_lines += ["  home-manager.useUserPackages = true;"]
    if hm_lines or _has_section_brix(brix, "Home Manager"):
        lines += [_section("Home Manager")] + hm_lines

    lines += ["}", ""]

    content = "\n".join(lines)
    if brix:
        content = inject_brick_blocks(content, brix)
    return _add_version_hash(content, ftype="co")


def generate_flake_nix(data: dict, nixos_dir: "str | Path | None" = None) -> str:
    """Generate flake.nix from panel data.

    nixos_dir: kept for signature compatibility, no longer used for host scanning.
    Host data comes exclusively from data["flake_hosts"].
    """
    hostname    = data.get("hostname", "nixos") or "nixos"
    description = data.get("flake_description") or f"NixOS configuration for {hostname}"
    channel     = data.get("flake_nixpkgs_channel") or "nixos-unstable"
    arch        = data.get("flake_arch") or "x86_64-linux"
    hm_input    = bool(data.get("flake_hm_input"))
    hm_follows  = bool(data.get("flake_hm_follows", True))
    hm_module   = bool(data.get("flake_hm_module", True))
    hw_input    = bool(data.get("flake_nixos_hardware"))
    pm_input    = bool(data.get("flake_plasma_manager"))

    flake_hosts: list[dict] = data.get("flake_hosts") or []
    brix = dict(data.get("flake_brick_blocks", {}))

    # Legacy: if "outputs-declaration" Brix in "Outputs" section exists, the
    # entire outputs block is managed by that Brix.
    has_outputs_declaration = (
        "outputs-declaration" in brix
        and brix["outputs-declaration"].get("section") == "Outputs"
    )

    # ── inputs block ──────────────────────────────────────────────────────────
    inp: list[str] = [f'    nixpkgs.url = "github:NixOS/nixpkgs/{channel}";']
    if hm_input:
        if hm_follows:
            inp += [
                '    home-manager = {',
                '      url = "github:nix-community/home-manager";',
                '      inputs.nixpkgs.follows = "nixpkgs";',
                '    };',
            ]
        else:
            inp.append('    home-manager.url = "github:nix-community/home-manager";')
    if hw_input:
        inp.append('    nixos-hardware.url = "github:NixOS/nixos-hardware";')
    if pm_input:
        inp += [
            '    plasma-manager = {',
            '      url = "github:nix-community/plasma-manager";',
            '      inputs.nixpkgs.follows = "nixpkgs";',
            '      inputs.home-manager.follows = "home-manager";',
            '    };',
        ]

    inputs_block = "\n".join(inp)

    # ── build content ─────────────────────────────────────────────────────────
    content = (
        "# Generated by NiCo – NixOS Configurator\n"
        "{\n"
        + _section("Start") + "\n"
        + f'  description = "{description}";\n'
        + _section("Inputs") + "\n"
        + "  inputs = {\n"
        + f"{inputs_block}\n"
        + _section("Inputs-Extra") + "\n"
        + "  };\n"
    )

    if has_outputs_declaration:
        # Legacy: whole outputs provided by Brix
        content += _section("Outputs") + "\n"
    else:
        # ── outputs args ──────────────────────────────────────────────────────
        out_args: list[str] = ["self", "nixpkgs"]
        if hm_input:
            out_args.append("home-manager")
        if hw_input:
            out_args.append("nixos-hardware")
        if pm_input:
            out_args.append("plasma-manager")
        out_args_str = ", ".join(out_args) + ", ..."

        def _host_header(name: str) -> str:
            dashes = "─" * max(1, _MARKER_WIDTH - len(f"Host: {name}") - 10)
            return f"      # ── Host: {name} {dashes}"

        def _default_host_body(name: str) -> str:
            body = [
                f'      system = "{arch}";',
                "      modules = [",
                "        ./configuration.nix",
                f"        ./hosts/{name}/hardware-configuration.nix",
                f"        ./hosts/{name}",
            ]
            if hm_input and hm_module:
                body.append("        home-manager.nixosModules.home-manager")
            body += ["      ];"]
            return "\n".join(body)

        def _ensure_host_brix(name: str) -> None:
            section = flake_host_section(name)
            if any(block.get("section") == section for block in brix.values()):
                return
            brick_name = flake_host_brick_name(name)
            suffix = 2
            while brick_name in brix:
                brick_name = f"{flake_host_brick_name(name)}-{suffix}"
                suffix += 1
            brix[brick_name] = {
                "section": section,
                "order": 1,
                "text": format_brick(section, 1, brick_name, _default_host_body(name)),
            }

        def _host_entry(h: dict) -> str:
            hname = h["name"]
            _ensure_host_brix(hname)
            return (
                f"    {hname} = nixpkgs.lib.nixosSystem {{\n"
                + _host_header(hname)
                + "\n"
                + "    };"
            )

        if flake_hosts:
            cfg_block = "\n".join(_host_entry(h) for h in flake_hosts)
        else:
            cfg_block = _host_entry({"name": hostname})

        content += (
            _section("Outputs") + "\n"
            + f"  outputs = {{ {out_args_str} }}: {{\n"
            + "    nixosConfigurations = {\n"
            + _section("Outputs-Hosts") + "\n"
            + f"{cfg_block}\n"
            + "    };\n"
            + _section("Outputs-Extra") + "\n"
            + "  };\n"
        )

    content += "\n}\n"

    if brix:
        content = inject_brick_blocks(content, brix)
    return _add_version_hash(content, ftype="fl")
