"""
Home Manager configuration generator.

Generates a home.nix file from NiCo's Home Manager config data.
This module is wired into the GUI via the HM file browser panel.

Supported options (initial set, covering the most common 80/20 needs):
  - programs.git            (name, email, defaultBranch)
  - programs.bash/zsh/fish  (enable + init extras)
  - home.packages           (list of pkgs attr names)
  - programs.firefox        (enable)
  - xdg.userDirs            (standard XDG directories)
  - home.stateVersion       (required by Home Manager)
  - home.username / home.homeDirectory

Data shape (as stored in nico.json under the key "home_manager"):
{
  "enabled":          false,        # master switch
  "username":         "",           # must match the system user
  "home_dir":         "",           # e.g. /home/alice
  "state_version":    "24.11",

  "git_enable":       false,
  "git_name":         "",
  "git_email":        "",
  "git_default_branch": "main",

  "shell":            "bash",       # bash | zsh | fish
  "shell_init_extra": "",           # appended to the shell init file

  "packages":         [],           # list of pkgs attr names (strings)

  "firefox":          false,

  "xdg_user_dirs":    false,        # enable xdg.userDirs
  "xdg_download":     "Downloads",
  "xdg_documents":    "Documents",
  "xdg_pictures":     "Pictures",
  "xdg_music":        "Music",
  "xdg_videos":       "Videos",
  "xdg_desktop":      "Desktop",
  "xdg_templates":    "Templates",
  "xdg_publicshare":  "Public",
}

Usage:
  from nico.hm_generator import generate_home_nix
  nix_text = generate_home_nix(data["home_manager"])
"""

import hashlib

from .brix import inject_brick_blocks

_MARKER_WIDTH = 78


def _hm_section_top(name: str) -> str:
    """Top-level section marker (no indent): # ── Name ─────────────"""
    dashes = "─" * max(1, _MARKER_WIDTH - len(name) - 6)
    return f"# ── {name} {dashes}"


def _hm_section(name: str) -> str:
    """Indented section marker for inside {}: # ── Name ─────────────"""
    dashes = "─" * max(1, _MARKER_WIDTH - len(name) - 6)
    return f"  # ── {name} {dashes}"


def _add_hm_version_hash(content: str, ftype: str = "hm") -> str:
    """Insert '# nico-version: [type#]<hash>' on line 2 of content."""
    h = hashlib.sha256(content.encode()).hexdigest()[:8]
    lines = content.split("\n")
    prefix = f"{ftype}#" if ftype else ""
    lines.insert(1, f"# nico-version: {prefix}{h}")
    return "\n".join(lines)


# Default values so callers can pass a partial dict
HM_DEFAULTS: dict = {
    "enabled":            False,
    "username":           "",
    "home_dir":           "",
    "state_version":      "24.11",

    "git_enable":         False,
    "git_name":           "",
    "git_email":          "",
    "git_default_branch": "main",

    "shell":              "bash",
    "shell_init_extra":   "",

    "packages":           [],

    "firefox":            False,

    "xdg_user_dirs":      False,
    "xdg_download":       "Downloads",
    "xdg_documents":      "Documents",
    "xdg_pictures":       "Pictures",
    "xdg_music":          "Music",
    "xdg_videos":         "Videos",
    "xdg_desktop":        "Desktop",
    "xdg_templates":      "Templates",
    "xdg_publicshare":    "Public",
}


HM_SECTION_START = "Start"
HM_SECTION_MAIN = "Home Manager"
HM_SECTION_END = "End"


def _g(data: dict, key: str):
    """Get a value from data, falling back to HM_DEFAULTS."""
    return data.get(key, HM_DEFAULTS.get(key))


def generate_home_nix(data: dict) -> str:
    """
    Generate a home.nix string from the given Home Manager config dict.
    Missing keys fall back to HM_DEFAULTS.
    Returns a complete, standalone home.nix that can be imported by
    Home Manager (standalone or as a NixOS module).
    """
    username      = _g(data, "username")      or "user"
    home_dir      = _g(data, "home_dir")      or f"/home/{username}"
    state_version = _g(data, "state_version") or "24.11"

    git_enable    = _g(data, "git_enable")
    git_name      = _g(data, "git_name")
    git_email     = _g(data, "git_email")
    git_branch    = _g(data, "git_default_branch") or "main"

    shell         = _g(data, "shell") or "bash"
    shell_extra   = (_g(data, "shell_init_extra") or "").strip()

    packages      = _g(data, "packages") or []
    firefox       = _g(data, "firefox")

    xdg_dirs      = _g(data, "xdg_user_dirs")
    brix          = data.get("hm_brick_blocks", {})

    lines = [
        "# Generated by NiCo – NixOS Configurator (Home Manager)",
        "# Do not edit manually. Use NiCo or add custom options via Nix-Brix.",
        _hm_section_top(HM_SECTION_START),
        "{ config, pkgs, lib, ... }:",
        "{",
        _hm_section(HM_SECTION_MAIN),
    ]

    # ── Identity ─────────────────────────────────────────────────────────
    lines += [
        f'  home.username      = "{username}";',
        f'  home.homeDirectory = "{home_dir}";',
    ]

    # ── Packages ─────────────────────────────────────────────────────────
    if packages:
        pkg_lines = "\n".join(f"    pkgs.{attr}" for attr in sorted(packages))
        lines += [
            "",
            "  home.packages = [",
            pkg_lines,
            "  ];",
        ]

    # ── Git ───────────────────────────────────────────────────────────────
    if git_enable:
        lines += ["", "  programs.git = {", "    enable = true;"]
        if git_name:
            lines += [f'    userName  = "{git_name}";']
        if git_email:
            lines += [f'    userEmail = "{git_email}";']
        lines += [
            "    extraConfig = {",
            f'      init.defaultBranch = "{git_branch}";',
            "    };",
            "  };",
        ]

    # ── Shell ─────────────────────────────────────────────────────────────
    if shell in ("bash", "zsh", "fish"):
        lines += ["", f"  programs.{shell} = {{", "    enable = true;"]
        if shell_extra:
            extra_key = {
                "bash": "initExtra",
                "zsh":  "initExtra",
                "fish": "shellInit",
            }[shell]
            # Indent each line of the extra content
            indented = "\n".join(f"      {ln}" for ln in shell_extra.splitlines())
            lines += [
                f"    {extra_key} = ''",
                indented,
                "    '';",
            ]
        lines += ["  };"]

    # ── Firefox ───────────────────────────────────────────────────────────
    if firefox:
        lines += ["", "  programs.firefox.enable = true;"]

    # ── XDG user directories ─────────────────────────────────────────────
    if xdg_dirs:
        lines += [
            "",
            "  xdg.userDirs = {",
            "    enable     = true;",
            "    createDirectories = true;",
            f'    download   = "${{config.home.homeDirectory}}/{_g(data, "xdg_download")}";',
            f'    documents  = "${{config.home.homeDirectory}}/{_g(data, "xdg_documents")}";',
            f'    pictures   = "${{config.home.homeDirectory}}/{_g(data, "xdg_pictures")}";',
            f'    music      = "${{config.home.homeDirectory}}/{_g(data, "xdg_music")}";',
            f'    videos     = "${{config.home.homeDirectory}}/{_g(data, "xdg_videos")}";',
            f'    desktop    = "${{config.home.homeDirectory}}/{_g(data, "xdg_desktop")}";',
            f'    templates  = "${{config.home.homeDirectory}}/{_g(data, "xdg_templates")}";',
            f'    publicShare = "${{config.home.homeDirectory}}/{_g(data, "xdg_publicshare")}";',
            "  };",
        ]

    # ── Required stateVersion ────────────────────────────────────────────
    lines += [
        f'  home.stateVersion = "{state_version}";',
        _hm_section(HM_SECTION_END),
        "",
        "}",
        "",
    ]
    content = "\n".join(lines)
    if brix:
        content = inject_brick_blocks(content, brix)
    return _add_hm_version_hash(content, ftype="hm")
