"""
Import: liest eine bestehende configuration.nix und überträgt bekannte Felder
in nico.json.  Unbekannter Inhalt landet als Brix damit nichts verloren geht.

Strategie:
  1. Quelle in Top-Level-Bindings zerlegen: bevorzugt per tree-sitter
     (nix_parser), sonst Regex-Fallback (_rx_top_level_bindings).
  2. Gemeinsame Feld-Map (_extract_fields) bildet Bindings auf NiCo-Felder ab –
     eine einzige Spezifikation für beide Pfade.
  3. Nicht konsumierte Bindings werden als Brix-Blöcke gesichert.
"""

import re
import shutil
from pathlib import Path
from .brix import strip_brick_blocks

ETC_NIXOS = Path("/etc/nixos")
_NICO_COMMENT_LINE_RE = re.compile(
    r'^\s*#\s*(?:'
    r'Generated by NiCo\b.*|'
    r'nico-version:.*|'
    r'Do not edit manually\..*|'
    r'<brick:.*|'
    r'</brick:.*|'
    r'<brix:.*|'
    r'</brix:.*|'
    r'──+.*'
    r')\s*$'
)


# ── helpers ───────────────────────────────────────────────────────────────────

def _strip_nix_comments(text: str) -> str:
    text = re.sub(r'/\*.*?\*/', '', text, flags=re.DOTALL)
    text = re.sub(r'#(?!\s*</?bri(?:x|ck):)[^\n]*', '', text)
    return text


def _split_top_level_stmts(content: str) -> list[str]:
    # A depth-0 semicolon usually ends a statement – except when it closes a
    # pending 'with expr;' / 'assert cond;' inside the current value
    # (e.g. environment.systemPackages = with pkgs; [ ... ];).
    statements, depth, start, pending = [], 0, 0, 0
    i, n = 0, len(content)
    while i < n:
        ch = content[i]
        if ch in ('{', '[', '('):
            depth += 1
        elif ch in ('}', ']', ')'):
            depth -= 1
        elif depth == 0 and ch in ('w', 'a'):
            m = re.match(r'(?:with|assert)\b', content[i:])
            if m and (i == 0 or not (content[i - 1].isalnum() or content[i - 1] in '._-')):
                pending += 1
                i += m.end()
                continue
        elif ch == ';' and depth == 0:
            if pending:
                pending -= 1
            else:
                stmt = content[start:i + 1].strip()
                if stmt:
                    statements.append(stmt)
                start = i + 1
                pending = 0
        i += 1
    leftover = content[start:].strip()
    if leftover:
        statements.append(leftover)
    return statements


def _brix_name_from_stmt(stmt: str) -> str:
    m = re.match(r'\s*([\w.\-]+)', stmt)
    return m.group(1).replace('.', '-') if m else 'imported'

# ── shared field map ──────────────────────────────────────────────────────────

def _extract_fields(kv: 'dict[str, str]', clean: str) -> 'tuple[dict, set[str]]':
    """
    Single source of truth for the Nix-option → NiCo-field mapping.
    kv maps top-level binding keys to raw value text; it may come from
    tree-sitter (nix_parser.make_kv) or from the regex fallback
    (_rx_top_level_bindings), so the field map exists exactly once.
    clean: brick-stripped source, only used for non-binding extras (nix_args).
    Returns (recognized_dict, consumed_binding_keys).
    """
    from . import nix_parser as _np  # only pure value helpers, no grammar needed

    consumed: set[str] = set()
    r: dict = {}

    def _vt(nix_key: str) -> 'str | None':
        """Flat lookup, then block fallback trying all possible parent prefixes."""
        if nix_key in kv:
            return kv[nix_key]
        # Try every split point from longest parent to shortest.
        # e.g. services.pipewire.alsa.support32Bit:
        #   parent=services.pipewire.alsa / child=support32Bit       → not in kv
        #   parent=services.pipewire     / child=alsa.support32Bit   → in kv → search inner
        key_parts = nix_key.split('.')
        for i in range(len(key_parts) - 1, 0, -1):
            parent = '.'.join(key_parts[:i])
            child  = '.'.join(key_parts[i:])
            if parent in kv:
                inner = _np.extract_inner_block(kv[parent])
                if inner:
                    m = re.search(
                        rf'(?<![.\w]){re.escape(child)}'
                        r'\s*=\s*([^;{]+|\{[^{}]*\})\s*;',
                        inner,
                    )
                    if m:
                        return m.group(1).strip()
        return None

    def _mark(nix_key: str):
        if nix_key in kv:
            consumed.add(nix_key)
            return
        parts = nix_key.split('.')
        for i in range(len(parts) - 1, 0, -1):
            parent = '.'.join(parts[:i])
            if parent in kv:
                consumed.add(parent)
                return

    def s(nico_key, *nix_keys):
        for nk in nix_keys:
            vt = _vt(nk)
            if vt is not None:
                v = _np.extract_string(vt)
                if v is not None:
                    r[nico_key] = v; _mark(nk); return

    def b(nico_key, *nix_keys):
        for nk in nix_keys:
            vt = _vt(nk)
            if vt is not None:
                v = _np.extract_bool(vt)
                if v is not None:
                    r[nico_key] = v; _mark(nk); return

    # ── Module args (regex – not a standard binding) ──────────────────────────
    m_args = re.search(r'^\s*\{\s*([^}]+)\s*\}\s*:', clean, re.MULTILINE)
    if m_args:
        args_clean = ', '.join(a.strip() for a in m_args.group(1).split(',') if a.strip())
        if args_clean:
            r['nix_args'] = args_clean

    # ── System ────────────────────────────────────────────────────────────────
    s('hostname',      'networking.hostName')
    s('state_version', 'system.stateVersion')
    b('allowUnfree',   'nixpkgs.config.allowUnfree')

    # ── Lokalisierung ─────────────────────────────────────────────────────────
    s('timezone', 'time.timeZone')
    s('locale',   'i18n.defaultLocale')

    vt = _vt('i18n.extraLocaleSettings')
    if vt is not None:
        inner = _np.extract_inner_block(vt) or vt
        m = re.search(r'LC_\w+\s*=\s*"([^"]*)"', inner)
        if m:
            r['extra_locale'] = m.group(1); _mark('i18n.extraLocaleSettings')

    xkb_vt = _vt('services.xserver.xkb')
    if xkb_vt:
        inner = _np.extract_inner_block(xkb_vt) or ''
        for attr, nico_k in [('layout', 'keyboard_layout'), ('variant', 'keyboard_variant')]:
            m = re.search(rf'{attr}\s*=\s*"([^"]*)"', inner)
            if m:
                r[nico_k] = m.group(1); _mark('services.xserver.xkb')
    else:
        s('keyboard_layout',  'services.xserver.xkb.layout')
        s('keyboard_variant', 'services.xserver.xkb.variant')
    s('keyboard_console', 'console.keyMap')

    # ── Boot ──────────────────────────────────────────────────────────────────
    for loader_key, loader_name in [
        ('boot.loader.systemd-boot.enable', 'systemd-boot'),
        ('boot.loader.grub.enable',         'grub'),
    ]:
        vt = _vt(loader_key)
        if vt and _np.extract_bool(vt):
            r['boot_loader'] = loader_name; _mark(loader_key); break

    b('boot_efi_can_touch',   'boot.loader.efi.canTouchEfiVariables')
    s('boot_efi_mount_point', 'boot.loader.efi.efiSysMountPoint')
    vt = _vt('boot.loader.systemd-boot.configurationLimit')
    if vt:
        v = _np.extract_int(vt)
        if v is not None:
            r['boot_config_limit'] = v; _mark('boot.loader.systemd-boot.configurationLimit')

    vt = _vt('boot.kernelParams')
    if vt:
        inner = vt.strip()
        if inner.startswith('[') and inner.endswith(']'):
            params = re.findall(r'"([^"]*)"', inner)
            if params:
                r['boot_kernel_params'] = ' '.join(params); _mark('boot.kernelParams')

    b('boot_initrd_systemd', 'boot.initrd.systemd.enable')
    b('plymouth_enabled',    'boot.plymouth.enable')
    s('plymouth_theme',      'boot.plymouth.theme')

    # ── Netzwerk ──────────────────────────────────────────────────────────────
    b('networkmanager', 'networking.networkmanager.enable')
    b('ssh',            'services.openssh.enable')

    vt = _vt('networking.firewall.enable')
    if vt and _np.extract_bool(vt) is False:
        r['firewall_disable'] = True; _mark('networking.firewall.enable')

    for nico_tcp_udp, fw_key in [
        (('firewall_tcp_ports', 'firewall_tcp_enable'), 'networking.firewall.allowedTCPPorts'),
        (('firewall_udp_ports', 'firewall_udp_enable'), 'networking.firewall.allowedUDPPorts'),
    ]:
        ports_nico, enable_nico = nico_tcp_udp
        vt = kv.get(fw_key)
        if vt is not None:
            nums = re.findall(r'\d+', re.sub(r'#[^\n]*', '', vt))
            ports = ' '.join(nums)
            if ports:
                r[ports_nico] = ports; r[enable_nico] = True
                consumed.add(fw_key)

    # ── Services ──────────────────────────────────────────────────────────────
    b('printing', 'services.printing.enable')
    b('avahi',    'services.avahi.enable')
    b('bluetooth','hardware.bluetooth.enable')
    b('blueman',  'services.blueman.enable')
    b('libinput', 'services.libinput.enable')
    b('fprintd',  'services.fprintd.enable')
    b('pcscd',    'services.pcscd.enable')
    b('sunshine', 'services.sunshine.enable')

    # ── Audio ─────────────────────────────────────────────────────────────────
    b('pipewire',       'services.pipewire.enable')
    b('pipewire_32bit', 'services.pipewire.alsa.support32Bit')

    # ── Desktop ───────────────────────────────────────────────────────────────
    desktop_extra_keys = {
        'gnome':   ['services.xserver.enable', 'services.xserver.displayManager.gdm.enable'],
        'kde':     ['services.xserver.enable', 'services.displayManager.sddm.enable'],
        'plasma5': ['services.xserver.enable'],
        'xfce':    ['services.xserver.enable', 'services.xserver.displayManager.lightdm.enable'],
        'mate':    ['services.xserver.enable'],
        'lxqt':    ['services.xserver.enable'],
        'i3':      ['services.xserver.enable'],
        'sway':    [],
        'hyprland': [],
    }
    for de_name, de_key in [
        ('gnome',    'services.xserver.desktopManager.gnome.enable'),
        ('kde',      'services.desktopManager.plasma6.enable'),
        ('plasma5',  'services.xserver.desktopManager.plasma5.enable'),
        ('xfce',     'services.xserver.desktopManager.xfce.enable'),
        ('mate',     'services.xserver.desktopManager.mate.enable'),
        ('lxqt',     'services.xserver.desktopManager.lxqt.enable'),
        ('i3',       'services.xserver.windowManager.i3.enable'),
        ('sway',     'programs.sway.enable'),
        ('hyprland', 'programs.hyprland.enable'),
    ]:
        vt = _vt(de_key)
        if vt and _np.extract_bool(vt):
            r['desktop_environment'] = de_name
            _mark(de_key)
            for extra_key in desktop_extra_keys.get(de_name, []):
                _mark(extra_key)
            break

    if r.get('pipewire'):
        _mark('services.pulseaudio.enable')
        _mark('security.rtkit.enable')

    vt = _vt('services.displayManager.autoLogin')
    if vt:
        inner = _np.extract_inner_block(vt) or ''
        m = re.search(r'user\s*=\s*"([^"]*)"', inner)
        if m:
            r['autologin_user'] = m.group(1); _mark('services.displayManager.autoLogin')
    else:
        s('autologin_user',
          'services.displayManager.autoLogin.user',
          'services.xserver.displayManager.autoLogin.user')
    if 'autologin_user' in r:
        _mark('services.displayManager.autoLogin.enable')
        _mark('services.xserver.displayManager.autoLogin.enable')

    # ── System-Programme ──────────────────────────────────────────────────────
    b('steam',    'programs.steam.enable')
    b('appimage', 'programs.appimage.enable')

    ff_vt = _vt('programs.firefox')
    if ff_vt:
        inner = _np.extract_inner_block(ff_vt) or ''
        m = re.search(r'enable\s*=\s*(true|false)', inner)
        if m:
            r['firefox'] = (m.group(1) == 'true'); _mark('programs.firefox')
        m2 = re.search(r'languagePacks\s*=\s*\[([^\]]*)\]', inner)
        if m2:
            packs = re.findall(r'"([^"]+)"', m2.group(1))
            if packs: r['firefox_lang_packs'] = ', '.join(packs)
        m2 = re.search(r'preferences\s*=\s*\{([^}]*)\}', inner, re.DOTALL)
        if m2:
            lines = [l.strip() for l in m2.group(1).splitlines() if l.strip()]
            if lines: r['firefox_prefs'] = '\n'.join(lines)
    else:
        b('firefox', 'programs.firefox.enable')

    # ── Flatpak ───────────────────────────────────────────────────────────────
    b('flatpak_enable', 'services.flatpak.enable')
    fp_vt = _vt('systemd.services.flatpak-repo')
    if fp_vt:
        inner = _np.extract_inner_block(fp_vt) or fp_vt
        script_m = re.search(r"script\s*=\s*''(.*?)''", inner, re.DOTALL)
        if script_m:
            remotes = re.findall(
                r'flatpak\s+remote-add\s+--if-not-exists\s+(\S+)\s+(\S+)',
                script_m.group(1)
            )
            if remotes:
                r['flatpak_remotes'] = [{"name": n, "url": u} for n, u in remotes]
                _mark('systemd.services.flatpak-repo')

    # ── Pakete ────────────────────────────────────────────────────────────────
    if 'environment.systemPackages' in kv:
        pkgs_list = _np.extract_identifier_list(kv['environment.systemPackages']) or []
        r['packages'] = [{"attr": p, "enabled": True} for p in sorted(set(pkgs_list))]
        consumed.add('environment.systemPackages')

    # ── Schriftarten ──────────────────────────────────────────────────────────
    if 'fonts.packages' in kv:
        fonts_list = _np.extract_identifier_list(kv['fonts.packages']) or []
        if fonts_list:
            r['fonts'] = sorted(set(fonts_list))
        consumed.add('fonts.packages')

    # ── Nix & System ──────────────────────────────────────────────────────────
    b('nix_optimize_store', 'nix.settings.auto-optimise-store')

    vt = _vt('nix.settings.experimental-features')
    if vt and 'flakes' in vt:
        r['flakes'] = True; _mark('nix.settings.experimental-features')

    gc_vt = _vt('nix.gc')
    if gc_vt:
        inner = _np.extract_inner_block(gc_vt) or ''
        m = re.search(r'automatic\s*=\s*(true|false)', inner)
        if m: r['nix_gc'] = (m.group(1) == 'true')
        m = re.search(r'dates\s*=\s*"([^"]*)"', inner)
        if m: r['nix_gc_frequency'] = m.group(1)
        m = re.search(r'options\s*=\s*"--delete-older-than\s+([^"]+)"', inner)
        if m: r['nix_gc_age'] = m.group(1).strip()
        _mark('nix.gc')
    else:
        b('nix_gc', 'nix.gc.automatic')
        s('nix_gc_frequency', 'nix.gc.dates')
        vt = _vt('nix.gc.options')
        if vt:
            m = re.search(r'--delete-older-than\s+(\S+)', vt)
            if m: r['nix_gc_age'] = m.group(1); _mark('nix.gc.options')

    # ── Hardware ──────────────────────────────────────────────────────────────
    b('enable_all_firmware', 'hardware.enableAllFirmware')
    b('opengl',     'hardware.opengl.enable',        'hardware.graphics.enable')
    b('opengl_32bit','hardware.opengl.driSupport32Bit','hardware.graphics.enable32Bit')
    b('zram_swap',  'zramSwap.enable')
    b('openrgb',    'services.hardware.openrgb.enable')
    b('ledger',     'hardware.ledger.enable')
    b('ratbagd',    'services.ratbagd.enable')

    for cpu_type in ('intel', 'amd'):
        vt = _vt(f'hardware.cpu.{cpu_type}.updateMicrocode')
        if vt and _np.extract_bool(vt):
            r['cpu_microcode'] = cpu_type
            _mark(f'hardware.cpu.{cpu_type}.updateMicrocode')
            break

    # ── Virtualisierung ───────────────────────────────────────────────────────
    b('docker',               'virtualisation.docker.enable')
    b('docker_rootless',      'virtualisation.docker.rootless.enable')
    b('podman',               'virtualisation.podman.enable')
    b('podman_docker_compat', 'virtualisation.podman.dockerCompat')
    b('virtualbox_host',      'virtualisation.virtualbox.host.enable')
    b('virtualbox_guest',     'virtualisation.virtualbox.guest.enable')
    b('virtualbox_guest_drag_drop', 'virtualisation.virtualbox.guest.dragAndDrop')
    b('libvirtd',             'virtualisation.libvirtd.enable')
    b('virt_manager',         'programs.virt-manager.enable')

    # ── Dateisystem & Backup ──────────────────────────────────────────────────
    b('btrfs_scrub', 'services.btrfs.autoScrub.enable')

    _sn_prefix = 'services.snapper.configs.'
    _sn_cfgs = []
    for key in list(kv.keys()):
        if not key.startswith(_sn_prefix):
            continue
        cfg_name = key[len(_sn_prefix):]
        inner = _np.extract_inner_block(kv[key]) or kv[key]
        m_sub = re.search(r'SUBVOLUME\s*=\s*"([^"]*)"', inner)
        mountpoint = m_sub.group(1) if m_sub else ''
        sn_entry = {"name": cfg_name, "mountpoint": mountpoint,
                    "hourly": 5, "daily": 7, "weekly": 0, "monthly": 1, "yearly": 0}
        for fld, limit_key in [
            ('hourly',  'TIMELINE_LIMIT_HOURLY'),
            ('daily',   'TIMELINE_LIMIT_DAILY'),
            ('weekly',  'TIMELINE_LIMIT_WEEKLY'),
            ('monthly', 'TIMELINE_LIMIT_MONTHLY'),
            ('yearly',  'TIMELINE_LIMIT_YEARLY'),
        ]:
            m2 = re.search(rf'{limit_key}\s*=\s*(\d+)', inner)
            if m2:
                sn_entry[fld] = int(m2.group(1))
        _sn_cfgs.append(sn_entry)
        consumed.add(key)
    if _sn_cfgs:
        r['snapper_enable'] = True
        r['snapper_configs'] = _sn_cfgs

    # ── Benutzer ──────────────────────────────────────────────────────────────
    _EXCL   = {'root', 'nobody', 'guest', 'gast'}
    _SHELLS = {'pkgs.zsh': 'zsh', 'pkgs.fish': 'fish',
               'pkgs.bash': 'bash', 'pkgs.nushell': 'nushell'}

    user_bindings = sorted(
        [(k, v) for k, v in kv.items()
         if k.startswith('users.users.') and k.count('.') == 2],
        key=lambda x: x[0]
    )
    primary_done = False
    extra_users: list[dict] = []

    for user_key, user_vt in user_bindings:
        uname = user_key.split('.')[-1]
        if uname in _EXCL:
            continue
        inner = _np.extract_inner_block(user_vt) or user_vt
        consumed.add(user_key)

        def _ue(pattern, text=inner):
            m = re.search(pattern, text)
            return m.group(1) if m else None

        if not primary_done:
            primary_done = True
            r['username'] = uname
            v = _ue(r'description\s*=\s*"([^"]*)"')
            if v: r['user_description'] = v
            v = _ue(r'initialPassword\s*=\s*"([^"]*)"')
            if v: r['user_initial_password'] = v
            v = _ue(r'\buid\s*=\s*(\d+)')
            if v: r['user_uid'] = v
            v = _ue(r'\bshell\s*=\s*(pkgs\.\w+)')
            if v: r['user_shell'] = _SHELLS.get(v, 'bash')
            if r.get('user_shell') in ('zsh', 'fish'):
                _mark(f"programs.{r['user_shell']}.enable")
            m = re.search(r'extraGroups\s*=\s*\[([^\]]*)\]', inner)
            if m:
                groups = re.findall(r'"(\w+)"', m.group(1))
                if groups: r['user_groups'] = groups
        else:
            eu: dict = {'username': uname}
            v = _ue(r'description\s*=\s*"([^"]*)"')
            if v: eu['description'] = v
            v = _ue(r'initialPassword\s*=\s*"([^"]*)"')
            if v: eu['initial_password'] = v
            v = _ue(r'\buid\s*=\s*(\d+)')
            if v: eu['uid'] = int(v)
            v = _ue(r'\bshell\s*=\s*(pkgs\.\w+)')
            if v: eu['shell'] = _SHELLS.get(v, 'bash')
            m = re.search(r'extraGroups\s*=\s*\[([^\]]*)\]', inner)
            if m:
                groups = re.findall(r'"(\w+)"', m.group(1))
                if groups: eu['groups'] = groups
            extra_users.append(eu)

    if extra_users:
        r['extra_users'] = extra_users

    if 'users.users.gast' in kv:
        r['guest_user'] = True; consumed.add('users.users.gast')

    # ── Home Manager ──────────────────────────────────────────────────────────
    b('hm_use_global_pkgs',   'home-manager.useGlobalPkgs')
    b('hm_use_user_packages', 'home-manager.useUserPackages')

    if 'home-manager.sharedModules' in kv:
        vt = kv['home-manager.sharedModules']
        entries = re.findall(r'(\S+)', re.sub(r'[\[\]]', '', vt))
        if entries:
            plasma = 'plasma-manager.homeModules.plasma-manager'
            if plasma in entries:
                r['hm_plasma_manager'] = True
                extras = [e for e in entries if e != plasma]
            else:
                extras = entries
            if extras:
                r['hm_shared_modules_extra'] = '\n'.join(extras)
        consumed.add('home-manager.sharedModules')

    return r, consumed


def _wrap_brix(texts: 'list[str]') -> str:
    """Wrap statement texts as named brix blocks with duplicate-safe names."""
    used: dict[str, int] = {}
    parts = []
    for text in texts:
        base = _brix_name_from_stmt(text)
        if base in used:
            used[base] += 1
            name = f'{base}-{used[base]}'
        else:
            used[base] = 1
            name = base
        parts.append(f'# <brix: {name}>\n{text}\n# </brix: {name}>\n')
    return '\n'.join(parts)


def _rx_top_level_bindings(nix_content: str) -> 'tuple[dict[str, str], list[tuple[str | None, str]]]':
    """
    Regex fallback: split brick-stripped source into top-level bindings.
    Returns (kv, stmts) mirroring the shape of nix_parser.make_kv so the shared
    field map works on both paths.  stmts keeps source order as
    (binding_key or None, statement_text) for build_rest_brix.
    """
    content = strip_brick_blocks(nix_content)
    content = _strip_nix_comments(content).strip()
    # function header  { config, pkgs, ... }:
    content = re.sub(r'^\{[^}]*\}\s*:\s*', '', content, flags=re.DOTALL).strip()
    # outer braces of the top-level attribute set
    if content.startswith('{') and content.endswith('}'):
        content = content[1:-1]

    kv: dict[str, str] = {}
    stmts: 'list[tuple[str | None, str]]' = []
    for stmt in _split_top_level_stmts(content):
        m = re.match(r'([\w."\-]+)\s*=\s*(.*?)\s*;?\s*$', stmt, re.DOTALL)
        if m:
            kv[m.group(1)] = m.group(2)
            stmts.append((m.group(1), stmt))
        else:
            stmts.append((None, stmt))
    return kv, stmts


# ── tree-sitter based parse/brix (with regex fallback) ───────────────────────

def _ts_parse_config(nix_content: str) -> 'tuple[dict, set[str]] | None':
    """
    Tree-sitter based parse_config.
    Returns (recognized_dict, consumed_binding_keys) or None when unavailable.
    consumed_binding_keys: set of top-level binding keys that were mapped.
    """
    from . import nix_parser as _np

    clean   = strip_brick_blocks(nix_content)
    result  = _np.parse(clean)
    if not result.available:
        return None
    return _extract_fields(_np.make_kv(result), clean)


def _ts_build_rest_brix(nix_content: str, consumed: set[str]) -> 'str | None':
    """
    Tree-sitter based build_rest_brix.
    Wraps all unclaimed top-level bindings as brix blocks.
    Returns formatted string or None when unavailable.
    """
    from . import nix_parser as _np

    clean  = strip_brick_blocks(nix_content).strip()
    result = _np.parse(clean)
    if not result.available:
        return None

    all_bindings = result.known + result.unknown
    unclaimed    = [bi for bi in all_bindings if bi.key not in consumed]

    if not unclaimed:
        return ''
    return _wrap_brix([bi.full_text for bi in unclaimed])


# ── public API ────────────────────────────────────────────────────────────────

def check_import_available() -> bool:
    f = ETC_NIXOS / "configuration.nix"
    try:
        return f.is_file() and f.stat().st_size > 0
    except OSError:
        return False


def has_hardware_config() -> bool:
    return (ETC_NIXOS / "hardware-configuration.nix").is_file()


def parse_config(nix_content: str) -> dict:
    """
    Extrahiert alle bekannten Felder aus nix_content.
    Gibt ein flaches Dict zurück das direkt in nico.json gemergt werden kann.
    Nur gefundene Schlüssel sind enthalten (keine Defaults).
    Tree-sitter wird bevorzugt; Regex-Fallback wenn nicht verfügbar.
    """
    ts = _ts_parse_config(nix_content)
    if ts is not None:
        return ts[0]

    kv, _stmts = _rx_top_level_bindings(nix_content)
    return _extract_fields(kv, strip_brick_blocks(nix_content))[0]


def build_rest_brix(nix_content: str, recognized: dict) -> str:
    """
    Gibt den Konfigurationsinhalt zurück nachdem alle erkannten Optionen entfernt wurden.
    Das Ergebnis wird in Brix-Marker eingewickelt.
    Gibt leeren String zurück wenn nichts Sinnvolles übrig bleibt.
    Tree-sitter wird bevorzugt; Regex-Fallback wenn nicht verfügbar.
    recognized wird nicht mehr benötigt (die konsumierten Bindings werden aus
    demselben Inhalt neu bestimmt); Parameter bleibt für API-Kompatibilität.
    """
    ts = _ts_parse_config(nix_content)
    if ts is not None:
        result = _ts_build_rest_brix(nix_content, ts[1])
        if result is not None:
            return result

    kv, stmts = _rx_top_level_bindings(nix_content)
    consumed = _extract_fields(kv, strip_brick_blocks(nix_content))[1]
    unclaimed = [text for key, text in stmts if key is None or key not in consumed]
    if not unclaimed:
        return ''
    return _wrap_brix(unclaimed)


def parse_home_config(nix_content: str) -> dict:
    """Parse a NiCo-generated home.nix and return a home_manager dict.
    Only handles the fields that hm_generator.generate_home_nix writes."""
    from .hm_generator import HM_DEFAULTS

    r: dict = dict(HM_DEFAULTS)
    r["enabled"] = True
    core_args = {"config", "pkgs", "lib"}

    m_args = re.search(r'^\s*\{([^}]*)\}\s*:', nix_content, re.MULTILINE)
    if m_args:
        r["args"] = [
            arg.strip()
            for arg in m_args.group(1).split(',')
            if arg.strip()
            and arg.strip() != '...'
            and arg.strip() not in core_args
        ]

    def _s(pat: str) -> str | None:
        m = re.search(pat, nix_content, re.DOTALL | re.MULTILINE)
        return m.group(1).strip() if m else None

    v = _s(r'home\.username\s*=\s*"([^"]*)"')
    if v: r["username"] = v

    v = _s(r'home\.homeDirectory\s*=\s*"([^"]*)"')
    if v: r["home_dir"] = v

    v = _s(r'home\.stateVersion\s*=\s*"([^"]*)"')
    if v: r["state_version"] = v

    # Git
    if re.search(r'programs\.git\s*=\s*\{', nix_content):
        r["git_enable"] = True
        v = _s(r'userName\s*=\s*"([^"]*)"');        r["git_name"]           = v or r["git_name"]
        v = _s(r'userEmail\s*=\s*"([^"]*)"');       r["git_email"]          = v or r["git_email"]
        v = _s(r'defaultBranch\s*=\s*"([^"]*)"');   r["git_default_branch"] = v or r["git_default_branch"]

    # Shell (first match wins)
    for shell in ("bash", "zsh", "fish"):
        if re.search(rf'programs\.{shell}\s*=\s*\{{', nix_content):
            r["shell"] = shell
            key = {"bash": "initExtra", "zsh": "initExtra", "fish": "shellInit"}[shell]
            m2 = re.search(rf"{key}\s*=\s*''(.*?)''", nix_content, re.DOTALL)
            if m2:
                raw = m2.group(1).lstrip("\n").rstrip()
                if raw:
                    lines = raw.splitlines()
                    indent = min((len(l) - len(l.lstrip()) for l in lines if l.strip()), default=0)
                    r["shell_init_extra"] = "\n".join(l[indent:] for l in lines)
            break

    if re.search(r'programs\.firefox\.enable\s*=\s*true', nix_content):
        r["firefox"] = True

    # XDG user dirs
    if re.search(r'xdg\.userDirs\s*=\s*\{', nix_content):
        r["xdg_user_dirs"] = True
        for key, nix_key in [
            ("xdg_download",    "download"),
            ("xdg_documents",   "documents"),
            ("xdg_pictures",    "pictures"),
            ("xdg_music",       "music"),
            ("xdg_videos",      "videos"),
            ("xdg_desktop",     "desktop"),
            ("xdg_templates",   "templates"),
            ("xdg_publicshare", "publicShare"),
        ]:
            m2 = re.search(rf'{nix_key}\s*=\s*"\${{[^}}]*}}/([^"]+)"', nix_content)
            if m2: r[key] = m2.group(1)

    # Packages (pkgs.attrname)
    m_pkg = re.search(r'home\.packages\s*=\s*\[(.*?)\]', nix_content, re.DOTALL)
    if m_pkg:
        r["packages"] = re.findall(r'pkgs\.([\w_\-]+)', m_pkg.group(1))

    return r


def build_home_rest_brix(nix_content: str, recognized: dict) -> str:
    """Return unsupported Home Manager statements as legacy brix blocks."""
    content = strip_brick_blocks(nix_content)

    # Remove NiCo header comments, version line, section markers and wrapper.
    content = re.sub(r'^\s*# nico-version: .*$\n?', '', content, flags=re.MULTILINE)
    content = re.sub(r'^\s*# Generated by NiCo.*$\n?', '', content, flags=re.MULTILINE)
    content = re.sub(r'^\s*# Do not edit manually\..*$\n?', '', content, flags=re.MULTILINE)
    content = re.sub(r'^\s*#\s*──.*$\n?', '', content, flags=re.MULTILINE)
    content = re.sub(r'^(\s*#[^\n]*\n)+', '', content).lstrip()
    content = re.sub(r'^\s*\{[^}]*\}\s*:\s*', '', content, count=1).lstrip()
    if content.startswith('{'):
        content = content[1:]
    content = content.rstrip()
    if content.endswith('}'):
        content = content[:-1]

    def rm(pat: str):
        nonlocal content
        content = re.sub(pat, '', content, flags=re.DOTALL | re.MULTILINE)

    rm(r'\s*home\.username\s*=\s*"[^"]*"\s*;')
    rm(r'\s*home\.homeDirectory\s*=\s*"[^"]*"\s*;')
    rm(r'\s*home\.stateVersion\s*=\s*"[^"]*"\s*;')

    if recognized.get("packages"):
        rm(r'\s*home\.packages\s*=\s*\[(?:[^\]]|\](?=\s*;))*\]\s*;')
    if recognized.get("git_enable"):
        rm(r'\s*programs\.git\s*=\s*\{(?:[^{}]|\{[^{}]*\})*\}\s*;')
    shell = recognized.get("shell")
    if shell in ("bash", "zsh", "fish"):
        extra_key = {"bash": "initExtra", "zsh": "initExtra", "fish": "shellInit"}[shell]
        block_m = re.search(
            rf'programs\.{re.escape(shell)}\s*=\s*\{{((?:[^{{}}]|\{{[^{{}}]*\}})*)\}}',
            content, re.DOTALL
        )
        if block_m:
            inner = block_m.group(1)
            inner_check = re.sub(r'\s*enable\s*=\s*(?:true|false)\s*;', '', inner)
            inner_check = re.sub(
                rf'\s*{re.escape(extra_key)}\s*=\s*\'\'[\s\S]*?\'\'\s*;', '',
                inner_check
            )
            if inner_check.strip():
                # Block has unrecognized fields → keep as brix, skip regeneration
                recognized["shell"] = None
            else:
                rm(rf'\s*programs\.{re.escape(shell)}\s*=\s*\{{(?:[^{{}}]|\{{[^{{}}]*\}})*\}}\s*;')
        else:
            rm(rf'\s*programs\.{re.escape(shell)}\s*=\s*\{{(?:[^{{}}]|\{{[^{{}}]*\}})*\}}\s*;')
    if recognized.get("firefox"):
        rm(r'\s*programs\.firefox\.enable\s*=\s*true\s*;')
    if recognized.get("xdg_user_dirs"):
        rm(r'\s*xdg\.userDirs\s*=\s*\{(?:[^{}]|\{[^{}]*\})*\}\s*;')

    content = _strip_nix_comments(content)
    content = re.sub(r'\n{3,}', '\n\n', content).strip()
    if not content:
        return ''

    used: dict[str, int] = {}
    parts = []
    for stmt in _split_top_level_stmts(content):
        base = _brix_name_from_stmt(stmt)
        if base in used:
            used[base] += 1
            name = f'{base}-{used[base]}'
        else:
            used[base] = 1
            name = base
        parts.append(f'# <brix: {name}>\n{stmt}\n# </brix: {name}>\n')

    return '\n'.join(parts)


def dir_has_non_zip_files(nixos_dir: str | Path) -> bool:
    """True wenn nixos_dir mindestens eine relevante Nicht-ZIP-Datei enthält.
    Ausgenommen: nico.json (von NiCo angelegt), ZIP-Dateien, versteckte Dirs.
    """
    root = Path(nixos_dir)
    for f in root.rglob("*"):
        if not f.is_file():
            continue
        rel = f.relative_to(root)
        if f.suffix.lower() == ".zip":
            continue
        if any(part.startswith('.') for part in rel.parts):
            continue
        if str(rel) == "nico.json":
            continue
        return True
    return False


def backup_to_zip(nixos_dir: str | Path) -> str:
    """Packt alle relevanten Nicht-ZIP-Dateien in nixos_dir in eine ZIP.
    ZIP-Dateien und versteckte Verzeichnisse werden ausgelassen.
    Gibt den Dateinamen (relativ) zurück.
    """
    import zipfile as _zipfile
    from datetime import datetime as _dt
    root = Path(nixos_dir)
    ts = _dt.now().strftime("%Y-%m-%d-%H%M%S")
    zip_name = f"nixos-config-{ts}.zip"
    zip_path = root / zip_name
    with _zipfile.ZipFile(zip_path, "w", _zipfile.ZIP_DEFLATED) as zf:
        for f in sorted(root.rglob("*")):
            if not f.is_file():
                continue
            rel = f.relative_to(root)
            if f.suffix.lower() == ".zip":
                continue
            if any(part.startswith('.') for part in rel.parts):
                continue
            if str(rel) == "nico.json":
                continue  # add separately below
            zf.write(f, rel)
        # nico.json als Kopie beifügen (Referenz, wird beim Import nicht angewendet)
        nico_json = root / "nico.json"
        if nico_json.exists():
            zf.write(nico_json, "nico.json")
    return zip_name


def strip_nico_comment_lines(text: str) -> str:
    """Remove only NiCo-specific comment/marker lines from a .nix file."""
    lines = text.splitlines(keepends=True)
    kept: list[str] = []
    for line in lines:
        if _NICO_COMMENT_LINE_RE.match(line):
            continue
        kept.append(line)
    return ''.join(kept)


def scrub_nico_comments_in_tree(nixos_dir: str | Path) -> list[str]:
    """Remove NiCo comment/marker lines from all visible .nix files recursively.
    Returns relative file paths that changed.
    """
    root = Path(nixos_dir)
    changed: list[str] = []
    for f in sorted(root.rglob("*.nix")):
        if not f.is_file():
            continue
        rel = f.relative_to(root)
        if any(part.startswith('.') for part in rel.parts):
            continue
        original = f.read_text(encoding="utf-8")
        cleaned = strip_nico_comment_lines(original)
        if cleaned == original:
            continue
        f.write_text(cleaned, encoding="utf-8")
        changed.append(str(rel))
    return changed


def parse_flake_nix(content: str) -> dict:
    """
    Liest eine flake.nix und extrahiert bekannte Felder als flake_*-Dict.
    Analog zu parse_config() für configuration.nix.
    """
    r: dict = {}

    # description
    m = re.search(r'description\s*=\s*"([^"]*)"', content)
    if m:
        r['flake_description'] = m.group(1)

    # nixpkgs channel (z.B. github:NixOS/nixpkgs/nixos-unstable)
    m = re.search(r'nixpkgs\.url\s*=\s*"github:NixOS/nixpkgs/([^"]+)"', content)
    if m:
        r['flake_nixpkgs_channel'] = m.group(1)

    # system architecture
    m = re.search(r'\bsystem\s*=\s*"([^"]+)"', content)
    if m:
        r['flake_arch'] = m.group(1)

    # home-manager input
    hm_url = bool(re.search(r'home-manager\s*[=.]', content))
    r['flake_hm_input'] = hm_url
    if hm_url:
        r['flake_hm_follows'] = bool(re.search(r'inputs\.nixpkgs\.follows', content))
        r['flake_hm_module']  = bool(re.search(r'home-manager\.nixosModules', content))

    # nixos-hardware input
    r['flake_nixos_hardware'] = bool(re.search(r'nixos-hardware\.url\s*=', content))

    # plasma-manager input
    r['flake_plasma_manager'] = bool(re.search(r'plasma-manager\s*[=.]', content))

    # Per-host data: only the host names remain panel-managed.
    flake_hosts: list[dict] = []
    for host_name, host_entry, sys_block in _iter_flake_hosts(content):
        flake_hosts.append({"name": host_name})
        if "flake_arch" not in r:
            arch_m = re.search(r'\bsystem\s*=\s*"([^"]+)"', sys_block)
            if arch_m:
                r["flake_arch"] = arch_m.group(1)
    if flake_hosts:
        r['flake_hosts'] = flake_hosts

    return r


# ── flake.nix Brix-Extraktion ─────────────────────────────────────────────────

def _flake_extract_block(content: str, keyword: str) -> str | None:
    """Find 'keyword = {' in content and return the full assignment including
    the closing '};', or None if not found.  Handles nested braces."""
    pat = re.compile(r'\b' + re.escape(keyword) + r'\s*=\s*\{')
    m = pat.search(content)
    if not m:
        return None
    start = m.start()
    depth = 0
    i = m.start(0)
    # walk from the opening '{' of the value
    brace_start = content.index('{', m.start())
    i = brace_start
    while i < len(content):
        if content[i] == '{':
            depth += 1
        elif content[i] == '}':
            depth -= 1
            if depth == 0:
                # include trailing ';' if present
                end = i + 1
                while end < len(content) and content[end] in ' \t':
                    end += 1
                if end < len(content) and content[end] == ';':
                    end += 1
                return content[start:end]
        i += 1
    return None


def _flake_split_attrs(block_content: str) -> list[str]:
    """Split the BODY of a Nix attribute set (without outer braces) into
    individual top-level attribute assignments.  Returns list of raw strings."""
    entries: list[str] = []
    depth = 0
    current: list[str] = []
    in_string = False
    in_indent_string = False
    in_comment = False
    i = 0
    while i < len(block_content):
        ch = block_content[i]

        if in_comment:
            current.append(ch)
            if ch == '\n':
                in_comment = False
            i += 1
            continue

        if in_string:
            current.append(ch)
            if ch == '\\' and i + 1 < len(block_content):
                current.append(block_content[i + 1])
                i += 2
                continue
            if ch == '"':
                in_string = False
            i += 1
            continue

        if in_indent_string:
            if block_content.startswith("''", i):
                current.append("''")
                in_indent_string = False
                i += 2
                continue
            current.append(ch)
            i += 1
            continue

        if block_content.startswith("''", i):
            current.append("''")
            in_indent_string = True
            i += 2
            continue

        if ch == '#':
            current.append(ch)
            in_comment = True
            i += 1
            continue

        if ch == '"':
            current.append(ch)
            in_string = True
            i += 1
            continue

        if ch in '{[(':
            depth += 1
        elif ch in '}])':
            depth -= 1
        current.append(ch)
        if depth == 0 and ch == ';':
            text = ''.join(current).strip()
            if text:
                entries.append(text)
            current = []
        i += 1
    leftover = ''.join(current).strip()
    if leftover:
        entries.append(leftover)
    return entries


def _flake_attr_name(assignment: str) -> str:
    """Extract the attribute name (first identifier) from an assignment string.
    Skips leading comment lines (e.g. section markers injected by _section())."""
    for line in assignment.splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith('#'):
            m = re.match(r'([\w-]+)', stripped)
            return m.group(1) if m else ''
    return ''


def flake_host_section(host_name: str) -> str:
    return f"Host: {host_name}"


def flake_host_brick_name(host_name: str) -> str:
    return f"host-{host_name}"


def _unique_brick_name(blocks: dict[str, dict], base: str) -> str:
    if base not in blocks:
        return base
    idx = 2
    while f"{base}-{idx}" in blocks:
        idx += 1
    return f"{base}-{idx}"


def _extract_nixos_system_block(host_entry: str) -> str | None:
    sys_m = re.search(r'nixosSystem\s*\{', host_entry)
    if not sys_m:
        return None
    sys_start = host_entry.index('{', sys_m.start())
    depth, idx = 0, sys_start
    while idx < len(host_entry):
        if host_entry[idx] == '{':
            depth += 1
        elif host_entry[idx] == '}':
            depth -= 1
            if depth == 0:
                return host_entry[sys_start:idx + 1]
        idx += 1
    return None


def _nixos_system_body(sys_block: str) -> str:
    body = sys_block[1:-1].strip("\n")
    return body.rstrip()


def _iter_flake_hosts(content: str) -> list[tuple[str, str, str]]:
    hosts: list[tuple[str, str, str]] = []
    outputs_m = re.search(r'\boutputs\s*=\s*\{[^}]*\}\s*:\s*\{', content)
    if not outputs_m:
        return hosts
    colon_pos = content.index(':', outputs_m.start())
    body_start = content.index('{', colon_pos)
    depth, i = 0, body_start
    while i < len(content):
        if content[i] == '{':
            depth += 1
        elif content[i] == '}':
            depth -= 1
            if depth == 0:
                body_end = i
                break
        i += 1
    else:
        body_end = len(content)
    outputs_body = content[body_start + 1:body_end]
    nixos_cfg = _flake_extract_block(outputs_body, "nixosConfigurations")
    if not nixos_cfg:
        return hosts
    cfg_open = nixos_cfg.index('{') + 1
    cfg_close = nixos_cfg.rindex('}')
    for host_entry in _flake_split_attrs(nixos_cfg[cfg_open:cfg_close]):
        host_name = _flake_attr_name(host_entry)
        if not host_name:
            continue
        sys_block = _extract_nixos_system_block(host_entry)
        if not sys_block:
            continue
        hosts.append((host_name, host_entry, sys_block))
    return hosts


# Known input names that NiCo manages via panel fields
_KNOWN_INPUTS = frozenset({"nixpkgs", "home-manager", "nixos-hardware", "plasma-manager"})

# Known output keys that NiCo manages (nixosConfigurations is generated from hosts)
_KNOWN_OUTPUTS = frozenset({"nixosConfigurations"})


def build_flake_brix(content: str) -> dict:
    """
    Parse a flake.nix and return a Brix-blocks dict for everything that cannot
    be represented in the NiCo flake panel.

    Logic:
    - Unknown inputs      → Brix in "Inputs-Extra"
    - Every detected host  → one complete host-body Brix in "Host: <name>"
    - Other output keys   → Brix in "Outputs-Extra"
    """
    from .brix import format_brick
    brix: dict = {}
    order_inputs       = 1
    order_outputs_extra = 1

    # ── inputs ────────────────────────────────────────────────────────────────
    inputs_block = _flake_extract_block(content, "inputs")
    if inputs_block:
        brace_open  = inputs_block.index('{') + 1
        brace_close = inputs_block.rindex('}')
        for entry in _flake_split_attrs(inputs_block[brace_open:brace_close]):
            name = _flake_attr_name(entry)
            if name and name not in _KNOWN_INPUTS:
                brix[name] = {
                    "section": "Inputs-Extra",
                    "order":   order_inputs,
                    "text":    format_brick("Inputs-Extra", order_inputs, name, entry),
                }
                order_inputs += 1

    # ── outputs ───────────────────────────────────────────────────────────────
    outputs_match = re.search(r'\boutputs\s*=\s*\{[^}]*\}\s*:\s*\{', content)
    if outputs_match:
        colon_pos  = content.index(':', outputs_match.start())
        body_start = content.index('{', colon_pos)
        depth, i   = 0, body_start
        while i < len(content):
            if content[i] == '{':
                depth += 1
            elif content[i] == '}':
                depth -= 1
                if depth == 0:
                    body_end = i
                    break
            i += 1
        else:
            body_end = len(content)
        outputs_body = content[body_start + 1:body_end]

        # Every detected host is conserved as one complete host-body brick.
        nixos_cfg = _flake_extract_block(outputs_body, "nixosConfigurations")
        if nixos_cfg:
            for host_name, _, sys_block in _iter_flake_hosts(content):
                section = flake_host_section(host_name)
                brick_name = flake_host_brick_name(host_name)
                body = _nixos_system_body(sys_block)
                brix[brick_name] = {
                    "section": section,
                    "order": 1,
                    "text": format_brick(section, 1, brick_name, body),
                }

        # Other output keys (formatter etc.) → "Outputs-Extra"
        for entry in _flake_split_attrs(outputs_body):
            name = _flake_attr_name(entry)
            if name and name not in _KNOWN_OUTPUTS:
                brix[name] = {
                    "section": "Outputs-Extra",
                    "order":   order_outputs_extra,
                    "text":    format_brick("Outputs-Extra", order_outputs_extra, name, entry),
                }
                order_outputs_extra += 1

    return brix


def ensure_flake_host_bricks(content: str, existing_blocks: dict[str, dict] | None = None) -> dict[str, dict]:
    """Ensure that every nixosConfigurations host has a dedicated host-body brick.

    Existing host-body bricks are preserved. Managed host bodies from older flake
    files are migrated into host-specific bricks on the fly.
    """
    from .brix import format_brick

    blocks = dict(existing_blocks or {})
    for host_name, _, sys_block in _iter_flake_hosts(content):
        section = flake_host_section(host_name)
        if any(b.get("section") == section for b in blocks.values()):
            continue
        brick_name = _unique_brick_name(blocks, flake_host_brick_name(host_name))
        body = _nixos_system_body(sys_block)
        blocks[brick_name] = {
            "section": section,
            "order": 1,
            "text": format_brick(section, 1, brick_name, body),
        }
    return blocks


def copy_nix_tree(source_dir: str | Path, nixos_dir: str | Path) -> list[str]:
    """
    1:1-Kopie aller *.nix- und *.lock-Dateien von source_dir nach nixos_dir.
    Bestehende *.nix- und *.lock-Dateien in nixos_dir werden zuerst gelöscht.

    Sonderfall: src == dst oder src liegt innerhalb von dst → kein Löschen,
    Dateien sind schon am richtigen Ort.
    """
    src = Path(source_dir).resolve()
    dst = Path(nixos_dir).resolve()

    # Selbstreferenz-Schutz: würde zuerst alle Dateien löschen, dann src leer vorfinden
    src_inside_dst = False
    try:
        src.relative_to(dst)
        src_inside_dst = True
    except ValueError:
        pass

    if src == dst or src_inside_dst:
        # Dateien sind bereits am richtigen Ort – nur Liste zurückgeben, nichts löschen/kopieren
        copied = []
        for f in sorted(src.rglob("*")):
            rel = f.relative_to(src)
            if f.is_file() and f.suffix in (".nix", ".lock"):
                if not any(p.startswith('.') for p in rel.parts):
                    copied.append(str(rel))
        return copied

    for existing in dst.rglob("*"):
        if existing.is_file() and existing.suffix in (".nix", ".lock"):
            existing.unlink()

    copied = []
    for f in sorted(src.rglob("*")):
        if f.is_file() and f.suffix in (".nix", ".lock"):
            rel = f.relative_to(src)
            dest_file = dst / rel
            dest_file.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(f, dest_file)
            copied.append(str(rel))
    return copied


def copy_hardware_config(nixos_dir: str, src_path: str | None = None) -> bool:
    src = Path(src_path) if src_path else (ETC_NIXOS / "hardware-configuration.nix")
    dst = Path(nixos_dir) / "hardware-configuration.nix"
    shutil.copy2(src, dst)
    return True


def find_hardware_configs() -> list[str]:
    """Return existing hardware-configuration.nix candidates from known local paths."""
    candidates: list[Path] = []
    seen: set[str] = set()

    direct_paths = [
        ETC_NIXOS / "hardware-configuration.nix",
    ]
    search_roots = [
        Path("/etc/nixos"),
        Path("/run/current-system"),
        Path("/nix/var/nix/profiles"),
    ]

    for path in direct_paths:
        try:
            if path.is_file():
                resolved = str(path.resolve())
                if resolved not in seen:
                    seen.add(resolved)
                    candidates.append(path.resolve())
        except OSError:
            continue

    for root in search_roots:
        try:
            if not root.exists():
                continue
            for path in root.rglob("hardware-configuration.nix"):
                if not path.is_file():
                    continue
                resolved = str(path.resolve())
                if resolved in seen:
                    continue
                seen.add(resolved)
                candidates.append(path.resolve())
        except (OSError, PermissionError):
            continue

    return [str(path) for path in sorted(candidates, key=lambda p: str(p))]
